### ISSUE TITLE
TV - Verify that all methods are implemented

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#108]
Verify that all methods below have been implemented.

TV
- [x] /tv/{id}
- [x] /tv/{id}/account_states
- [x] /tv/{id}/alternative_titles
- [x] /tv/{id}/changes
- [x] /tv/{id}/content_ratings
- [x] /tv/{id}/credits
- [x] /tv/{id}/external_ids
- [x] /tv/{id}/images
- [x] /tv/{id}/keywords
- [x] /tv/{id}/rating
- [x] /tv/{id}/similar
- [x] /tv/{id}/translations
- [x] /tv/{id}/videos
- [x] /tv/latest
- [x] /tv/on_the_air
- [x] /tv/airing_today
- [x] /tv/top_rated
- [x] /tv/popular

**Comment by LordMike** [comment]
@Naliath can you help with:
- /tv/{id}/rating
- /tv/{id}/account_states

I think both the tests and the actual code needs work.

**Comment by Naliath** [comment]
I'll take a look this evening
