### ISSUE TITLE
Remove GetGenres()

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#118]
Remove before the 0.9 release.
This method is obsolete.

**Comment by joebob49** [comment]
Mike:

Is movie.genres still valid? I assume so.

Joe

**Comment by LordMike** [comment]
It is, it has moved to another method specifically for `Movie Genres`.
https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/Client/TMDbClientGenres.cs#L36
