### ISSUE TITLE
Rename all tests to follow some naming convention

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#122]
Suggestion:

#### For all "method-able" clients
We need to differentiate between the different types of Clients. Some client methods follow a specific pattern (see also [tmdb-services](https://github.com/LordMike/TMDbLib/wiki/TMDb-Services#data)), e.g. for `Movie`: 
- `/movie/{id}` -- general case, accepts `append_to_response`
- `/movie/{id}/credits` -- specific property only

These can be tested in a specific way. For any of the "method-able" clients:
- `TestMoviesExtrasNone` -- tests without `append_to_response` **(does not test values)**
- `TestMoviesExtrasExclusive` -- tests individual `append_to_response` **(does not test values)**
- `TestMoviesExtrasAll` -- tests with all `append_to_response` set **(does not test values)**

For each method in these clients:
- `Test XXX Method YYY` -- naming
- `TestMoviesMethodMovieCasts` -- tests a specific method (that alone), **tests values**

For other methods in the `Movie` class that are not "method-able":
- `Test XXX Other YYY` -- naming
- `TestMoviesOtherLatest` -- tests a specific feature, **tests values**

#### Complete example for Movie with this naming:
- Test Class: `TMDbLibTests\Client\ClientMovieTests.cs`
- `TestMoviesExtrasNone` -- generic method tester
- `TestMoviesExtrasExclusive` -- generic method tester
- `TestMoviesExtrasAll` -- generic method tester
- `TestMoviesMethodAlternativeTitles` -- method
- `TestMoviesMethodCredits` -- method
- `TestMoviesMethodImages` -- method
- `TestMoviesMethodKeywords` -- method
- `TestMoviesMethodReleases` -- method
- `TestMoviesMethodVideos` -- method
- `TestMoviesMethodTranslations` -- method
- `TestMoviesMethodSimilarMovies` -- method
- `TestMoviesMethodReviews` -- method
- `TestMoviesMethodLists` -- method
- `TestMoviesMethodChanges` -- method
- `TestMoviesMethodAccountStates` -- method
- `TestMoviesOtherLatest` -- other method
- `TestMoviesOtherUpcoming` -- other method, can use a generic paging tester
- `TestMoviesOtherNowPlaying` -- other method, can use a generic paging tester
- `TestMoviesOtherPopular` -- other method, can use a generic paging tester
- `TestMoviesOtherTopRated` -- other method, can use a generic paging tester

**Comment by LordMike** [comment]
Is this too convoluted, @Naliath ?

**Comment by Naliath** [comment]
Fine for me, not sure this will cover all cases in all scenario's but I'd rather have long and complete name than a abbreviated one anyway. And some consistency in these things will give us a better overview

**Comment by joebob49** [comment]
Mike;

This solves the problems I was having as a wrapper newby back in the "old" days. That and the fact some things had gotten out of date. Big improvements since then. Thanks

Joe

**Comment by LordMike** [comment]
I realized after writing this, that maybe instead the efforts should be focused on naming the methods in the API, rather than in the tests. Because, as @Naliath says, it might be hard to cover all cases (and some places we do integration tests instead).
