### ISSUE TITLE
Trailer Uniqueness

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#126]
Mike;

FYI The new object/method for trailers is just fine at the wrapper level but be aware that Travis's "id" is NOT unique (have not checked "key"). On re-scraping trailers (for 14 hours) I hit a few id duplicates. Just so you know.

Joe

**Comment by LordMike** [comment]
You should post some of these observations to the Google+ group. 

In my experience, not everything Travis does is intentional :).

**Comment by LordMike** [comment]
... but I find it disturbing to have an "Id" that is *not* an "Identifier".

**Comment by LordMike** [comment]
You mean the `Video` objects?

E.g., /movie/47964/videos

	{
		"id" : 47964,
		"results" : [{
				"id" : "533ec6a7c3a368544800556f",
				"iso_639_1" : "en",
				"key" : "7EgVRvG2mM0",
				"name" : "A Good Day To Die Hard Official Trailer",
				"site" : "YouTube",
				"size" : 720,
				"type" : "Trailer"
			}
		]
	}

**Comment by LordMike** [comment]
@joebob49 could it be that the trailers you find to be duplicates, actually are the same trailers?

I'm thinking that two episodes or two movies could be referencing the same trailer.
