### ISSUE TITLE
Release 0.8.3

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#133]
I pushed 0.8.2.3-alpha to Nuget after merging all the PR's I made.
Should we move to 0.8.3, and release it officially?

I wonder how it will break existing projects.

@Naliath please comment :)

@joebob49, check out the 0.8.2.3-alpha.

**Comment by Naliath** [comment]
Hey, spent the weekend in Frankfurt so didn't get a chance to check any of this. I'd do the final release after we fix the issue with the account states (if this hasn't been dealth with yet)

**Comment by LordMike** [comment]
I left a link somewhere. Basically, its already done on tmdb, were just missing the session id?

**Comment by LordMike** [comment]
I suppose it also counts for Rating (albeit that may be a write-only method).

**Comment by LordMike** [comment]
@Naliath found it: #131

**Comment by LordMike** [comment]
Couldn't wait, @Naliath .. :)

**Comment by Naliath** [comment]
np, been way too busy last few weeks. Good work
