### ISSUE TITLE
Broken: .Results = 0 with SearchCollection (always)

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#139]
Hi

looks like search movie collections is broken. If i search a movie collection like "James Bond", the
SearchContainer.TotalResults = 1, but
SearchContainer.Results = 0.

This has worked in older releases.

**Comment by LordMike** [comment]
Which version are you using?
It works on my end, using the `master` branch (as well as `async`).

**Comment by DanCooper** [comment]
I'm using the Nuget version. It has been worked a long time, but now is broken.

**Comment by LordMike** [comment]
Which version. 0.8.2 ?

Mvh.
Michael

**Comment by DanCooper** [comment]
The lastet available on Nuget.

**Comment by LordMike** [comment]
And is that 0.7.7 (last stable) or 0.8.2.4-alpha (latest prerelease)?

**Comment by DanCooper** [comment]
0.8.x alpha

**Comment by LordMike** [comment]
I am unable to reproduce with 0.8.2.4-alpha. Can you provide example code?
I tried with:

    TMDbClient client = new TMDbClient("c6b31d1c....");
    SearchContainer<SearchResultCollection> result = client.SearchCollection("James Bond");
    Console.WriteLine(result.Results.Count);

**Comment by DanCooper** [comment]
Sorry, it works now. I have no idea why the same code has nod worked today.
