### ISSUE TITLE
Discrepancy between the GitHub repo and Nuget package

### ISSUE THREAD

**Issue by Venom1991** [LordMike/TMDbLib#147]
Hi,

First, I want to thank you for building this library, it is a great help. I only have couple of questions.
I've added version 0.8.3 from Nuget into my project but I'm also trying to learn the library by using the cloned GitHub repository at the same time. There seems to be quite a difference in the implementations. For instance, difference methods like SearchTvShow(): Nuget version has a Results member which is a list of SearchTv objects whereas the GitHub version has a Result member which return a SearchContainer where T is SearchTv. Also, the latter is an asynchronous implementation.
The classes also differ when it comes to their members:
http://i.imgur.com/DLrKUAS.png (upper one is Nuget, lower one is GitHub).

Am I missing something here, perhaps? Does the Nuget package need updating?

Funny thing is that the cloned repo's Assembly Info says that it's version 0.8.3.0, same as the Nuget one but there are obvious discrepancies.

**Comment by LordMike** [comment]
True. Currently we're moving to v. 0.9 which will be an async edition. You can find the current published version on the `stable` branch.

https://github.com/LordMike/TMDbLib/tree/stable

**Comment by LordMike** [comment]
But do report other issues you find :)
Thanks for using the library - I was a bit tired when I wrote that last comment :P
