### ISSUE TITLE
Credits and Images collections are null

### ISSUE THREAD

**Issue by mmaxwell1206** [LordMike/TMDbLib#150]
![favoritescreditsissue](https://cloud.githubusercontent.com/assets/14008320/9537277/3042a7b2-4d04-11e5-991c-44d37f8992d8.png)

I can't manage to get any credits or images using the wrapper. The collections are null.
Am I missing anything or is there different levels to the API keys and I don't have permission?

I'm developing in VB.NET in framework 4.5.

Thanks,
Matt Maxwell

**Comment by Naliath** [comment]
Did you include them?

Check the api sample, in this repo, it's in c# but you should be able to figure it out.
In any case you have the main request for a movie/tvshow and then in the API this wrapper is calling you have the extended calls that return the details you are refering too and many more. All these extended calls can be user sepratly or be included in one single call. 

To do this in the wrapper just pass then desired extention calls in the original request as enum flags, as stated previously check the repo for a sample. (VB.net example for flag enums:http://stackoverflow.com/questions/58517/combining-enums)

**Comment by mmaxwell1206** [comment]
Sweet! I did not see that as a parameter for the Get call.

Thank you so much! And great job on the wrapper. It's been a huge help.

-Matt Maxwell
