### ISSUE TITLE
How to get a list of actors with version 0.8.3

### ISSUE THREAD

**Issue by ORRNY66** [LordMike/TMDbLib#151]
Hello,
how to get to version 0.8.3 TMDbLib list actors. It works only with previous versions 0.7.0 - 0.7.6

TMDbClient client = new TMDbClient ("apikey");
Movie film = client.GetMovie (1858, MovieMethods.Casts);

Console.WriteLine("Movie title: {0}", movie.Title);
foreach (Cast cast in movie.Casts.Cast)
    Console.WriteLine("{0} - {1}", cast.Name, cast.Character);

**Comment by LordMike** [comment]
In version `0.8.3` with the following code:

    TMDbClient client = new TMDbClient("c6b31d1cdad6a56a23f0c913e2482a31");
    
    Movie movie = client.GetMovie(1858, MovieMethods.Credits);
    
    Console.WriteLine("Movie title: {0}", movie.Title);
    foreach (Cast cast in movie.Credits.Cast)
    	Console.WriteLine("{0} - {1}", cast.Name, cast.Character);

I get an output that looks like what I had in `0.7.6` using your code. (Note the name change of `Casts` to `Credits`).

In version 0.7.7 however, it gets weird.. Apparently it forgets to attach the API key to requests :|

**Comment by LordMike** [comment]
If this is still an issue, please reopen.
