### ISSUE TITLE
Missing: TV - Production Countries

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#153]
I'm not shure if this is only missing in your API or also in the TMDB API, but the website list "Production Contries" for tv shows (it's not documented in Apiary).
Can you check that and add it to your API if TMDB does support this inforamtions in the API?

**Comment by LordMike** [comment]
Do you have an example?

**Comment by DanCooper** [comment]
https://www.themoviedb.org/tv/1399-game-of-thrones/edit?active_nav_item=production_information
(need to be logged in to see the list)

**Comment by LordMike** [comment]
Can't find it anywhere in the docs or the output. They have `origin_country` and `production_companies` - but not `production_countries`

**Comment by DanCooper** [comment]
Ok, i have pushed an old thread on TMDB forum:
https://www.themoviedb.org/talk/5427067ac3a3680b1b000472

**Comment by LordMike** [comment]
Thanks. I also wrote on their google page, but never received a response. Iirc.

-----Original Message-----

**Comment by Naliath** [comment]
https://tmdb.lighthouseapp.com/projects/83077-api/tickets/513-add-production-countries-to-tv-series-response

**Comment by DanCooper** [comment]
Finally TMDb implemented this information to the database (see https://www.themoviedb.org/talk/5427067ac3a3680b1b000472?page=1)

**Comment by DanCooper** [comment]
bump :)

**Comment by LordMike** [comment]
Oh shoot - would you have the ability to make a PR with the fields?

**Comment by DanCooper** [comment]
PR?

**Comment by LordMike** [comment]
Pull request :)

**Comment by DanCooper** [comment]
lol...  :D
No sorry, I don't know enough about C # to do a reasonable PR.

**Comment by LordMike** [comment]
@DanCooper this should be live on [Githubs package feed](https://github.com/LordMike/TMDbLib/packages/691970) soon. 

I haven't yet worked up docs on how to use the github feed, but if you're able to, you can use it directly. :)

I think it'll be [1.7.7-alpha.11](url)
