### ISSUE TITLE
How to get a movie genre

### ISSUE THREAD

**Issue by Max45** [LordMike/TMDbLib#154]
Hello,
I'm trying to get a list of genres, but I've only got GenreIds.

 SearchContainer<MovieResult> result = client.GetMovieList(MovieListType.Popular, "en");
 foreach (MovieResult movie in result.Results)
 {
      List<int> data = movie.GenreIds;
      var IdGenres = string.Join(",", data);
      Console.WriteLine(movie.Title + " --- " + IdGenres);
 }

But how do I get the name of the genre. Thanks a lot

**Comment by LordMike** [comment]
Hi,

You will be able to get the Genres via another call, which will provide you with a Map of ID <-> Name. IIIRC it's called `GetGenres`.

Mike.

**Comment by Max45** [comment]
Thank you very much for your response.
Still, I had one question how to get the ID Collection film.

for example:

SearchContainer<SearchResultCollection> collectons = client.SearchCollection("Transformers: Age of Extinction");
foreach (SearchResultCollection _collection in collectons.Results)
    Console.WriteLine("Collection ID: {0}\nPart of the: {1}", _collection.Id, _collection.Name);

Collection ID is found, if the name of the film as: Transformers
Not when the film's title: Transformers: Age of Extinction

**Comment by LordMike** [comment]
Hi,

The search in collections does not search the collection's contents. It only searches the collections themselves. So you could go about creating a collection named `Transformers: Age of Extinction`, but that would be silly as it would only ever logically contain one movie.

Mike.
