### ISSUE TITLE
How do you Discover movies by genre?

### ISSUE THREAD

**Issue by michaeldestici** [LordMike/TMDbLib#155]
I am having a hard time with the Discover method. I am new to C#, so there's that. Could someone please show me an example of how to use the Discover method? Thanks.

**Comment by LordMike** [comment]
For version `0.8.3`.

    private static void Main(string[] args)
    {
        TMDbClient client = new TMDbClient("c6b31d1cdad6a56a...");
    
        SearchPerson bruceWillis = client.SearchPerson("Bruce Willis").Results.First();
    
        DiscoverMovie discover = client.DiscoverMovies();
        discover.IncludeWithAllOfCast(new[] { bruceWillis.Id });
    
        for (int i = 0; ; i++)
        {
            SearchContainer<SearchMovie> items = discover.Query(i);
            if (!items.Results.Any())
                break;
    
            foreach (SearchMovie movie in items.Results)
            {
                Console.WriteLine(movie.Title);
            }
        }
    }

I was certain, however, that I made DiscoverXXXX enumerable (so you could do `foreach(var movie in discover)`.. Must have dreamt of that..
