### ISSUE TITLE
not all requests works with RestSharp 105.2.3

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#156]
Looks like only
````
TMDBApi.Find(TMDbLib.Objects.Find.FindExternalSource.Imdb, imdbID)
````
and
````
TMDBApi.Find(TMDbLib.Objects.Find.FindExternalSource.TvDb, tvdbID)
````
does not work with latest RestSharp version.

I know that your API only need 104.4.0, but I thought I give notice to you.

**Comment by Naliath** [comment]
Plan is to move away from rest sharp entirely so this should not be an issue. (If anyone ever finds the time that is)
