### ISSUE TITLE
Alternate Tiltles of TV Shows returning incorrect values

### ISSUE THREAD

**Issue by SounakBanerjee** [LordMike/TMDbLib#157]
Eg. Retrieving alternate titles for 'Marvel's Daredevil', is returning 'Deep Purple...', which is incorrect.
I'm using the following function:

TvShow show = client.GetTvShow(videoId, TvShowMethods.Images);
 client.GetMovieAlternativeTitles(show.Id);

**Comment by SounakBanerjee** [comment]
Is there a way to get the complete cast of a TV Show, instead of just the last season. (As TheMovieDB Api does)

**Comment by Naliath** [comment]
If are searching for alternative movie titles with a series Id, you are going to have a bad time.
Check if a comparable method exists for series, else it might not be available or not implemented.

**Comment by SounakBanerjee** [comment]
Is there one specifically for TV? I see just this one, and I was under the impression it could be an overloaded one. That's why I was hoping the author might clarify.

**Comment by Naliath** [comment]
GetTvShowAlternativeTitles is in the source, I do not know what version you are using but if you build from the source in github it should work. Also the naming scheme is quite specific, if it says movie in the name that is what it will be searching for.

**Comment by SounakBanerjee** [comment]
Many thanks, Naliath. This helps a lot.
