### ISSUE TITLE
Performance - Looking for others that have squeezed performance out of full movie pull

### ISSUE THREAD

**Issue by jensenkd** [LordMike/TMDbLib#162]
I'm currently pulling the tmdb locally using this library.

workflow:

- Pull movies 1-latestId
-- foreach movie, pull genres, languages, countries, credits..

It's very slow and i'm trying to find ways to make this faster.

I'm thinking one approach might be to use a queue with multiple worker roles, picking off movies and processing them.

Any ideas?

**Comment by Naliath** [comment]
You will quickly run into the max allowed queries per time unit (check the site for details). You might be able to obtain a db dump from travis (check in the forums)
