### ISSUE TITLE
Move to HttpClient

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#164]
The entire project should move to .Net's own HttpClient and Newtonsoft.Json. This is to become PCL compatibly and W8/10 Universal App-compatible.

Relevant:
#44, #163

**Comment by LordMike** [comment]
@Naliath how does this look?
I moved the rest of the methods over.

I have not yet removed the Restsharp implementation, as we still expose some ratelimiting options, which have not been reimplemented.

**Comment by Naliath** [comment]
Looks good at first glance. Only comment I have is that it seems like there are a few .ConfigureAwait(false) missing on some of the awaited calls

**Comment by Naliath** [comment]
I saw your inital implementation after I created my own branch and since I don't have much time anyway I figured I would wait for yours. (First kid is due in a few weeks ;))

I'll take a look at the rate limiting this evening see if I can throw out the restsharp reference entirely

**Comment by LordMike** [comment]
@Naliath I went ahead and did something ... It seems to work.
Also, I realised that TMDb tells us how many seconds to wait, and that setting MaxRetry = 0 is the same as setting ThrowExceptions ... :)

I've reduced it a lot - also I finally removed the RestSharp reference.

**Comment by LordMike** [comment]
I found some bugs in the way I did it - so I rewrote the retry-logic.. Stand by :P

**Comment by LordMike** [comment]
Should be all good now, @Naliath

**Comment by Naliath** [comment]
added some comments to the individual checkins. My daughter was born last week and about 7 weeks early so I was busy before getting stuff ready but now everything has gone in overdrive :p

**Comment by LordMike** [comment]
Congratulations :)
I'll look at the stuff.

**Comment by LordMike** [comment]
PR #171
