### ISSUE TITLE
Create a form of automated test of ALL properties on all base types to ensure proper serialization

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#167]
I think this is a necessity to ensure that the move from Restsharp to Newtonsoft goes smoothly. If this can be done using reflection, we'll have an upside of being able to remove some of the existing tests.

Thoughts:
* We can do optimistic checking, where we only test if properties have values (not null, not zero), or for lists we can test if *any* item contains a value for a given property. Thereby proving that the property was *at some point* deserialized.
* We can use reflection to create large test cases testing all properties up against some defined data.

**Comment by Naliath** [comment]
Sounds nice, not sure how solid we can get this though. The media item we choose will change continuously like in our current tests so it's hard to really nail it down. And some fields are just empty for some items. On the other had if we run through a list of say 10 items the property should come back in one of them. 

I would not remove specific tests we have in favor of this, unless we can get it to work really well ;).

**Comment by LordMike** [comment]
Another issue is how to get the document which was parsed. Perhaps we can abstract the web-request so that the response is also stored elsewhere. Then in Unit tests, we'll overload the download method, keep the document and do some form of reflection-parsing / processing.

I'll put it on hold for now.
