### ISSUE TITLE
How to get a movie director

### ISSUE THREAD

**Issue by ORRNY66** [LordMike/TMDbLib#176]
Hello,
I need advice on how to get a movie director. I tried almost everything, but I do not know what to do. Thanks a lot.

`           Movie movie = client.GetMovie(157336, "en", MovieMethods.Credits);
            foreach (Crew result in movie.Credits.Crew)
            {
                Console.WriteLine(result.Name);
            }`

**Comment by LordMike** [comment]
Are you certain the director exists on that movie? From a glance ... It looks like the code is correct.

Reg.
Mike

-----Original Message-----

**Comment by ORRNY66** [comment]
Yes Use this code to get everything [https://www.themoviedb.org/movie/157336-interstellar/cast](url) . But there is some method by which I acquired only a film director. Thanks a lot

**Comment by LordMike** [comment]
The code you provided will list 108 crewmembers, where one of them is "Christopher Nolan" with the `Job` "Director". Is this not correct?

**Comment by ORRNY66** [comment]
Yes, it is okay. But I'm interested in whether it will get a list of 108 crew members just certain categories, for example, Directing, Writing. Using this code, I am able to get only actor to the list of 108 crew members. It is therefore somehow acquire only certain categories?

`Movie movie = client.GetMovie(157336, "en", MovieMethods.Credits);
 foreach (TMDbLib.Objects.Movies.Cast result in movie.Credits.Cast.Take(5))
 {
      Console.WriteLine(result.Name);        
 }`

**Comment by LordMike** [comment]
This is not possible using the TMDb API. So unfortunately not.

Sorry about that.

**Comment by ORRNY66** [comment]
I solved it. Maybe it can be useful to others.

`           string directingIds_15 = string.Empty;
            int temp = 0;

              for (int i = 0; i < movie.Credits.Crew.Count; i++)
              {
                  if (movie.Credits.Crew.ElementAt(i).Department == "Directing")
                  {
                      directingIds_15 += movie.Credits.Crew.ElementAt(i).Id.ToString() + "/";
                      temp++;
                  }
              }

              if (temp == 0)
              {
                  directingIds_15 = "null";
              }
              else
              {
                  directingIds_15 = directingIds_15.TrimEnd('/');
                  
              }`
