### ISSUE TITLE
Crash: "Error converting value {null} to type 'System.DateTime'. Path 'episodes[0].air_date', line 1, position 45."

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#177]
The API 0.9.0-alpha crash if I try to scrape the season 0 (season specials) from tv show "Homeland".

API Call:
`GetTvSeason(1407, 0, TMDbLib.Objects.TvShows.TvSeasonMethods.Credits Or TMDbLib.Objects.TvShows.TvSeasonMethods.ExternalIds)`

Exception:

`"Error converting value {null} to type 'System.DateTime'. Path 'episodes[0].air_date', line 1, position 45."`

**Comment by Naliath** [comment]
so basicly air_date needs to be nullable and this should be fixed

**Comment by Naliath** [comment]
8e93dd7ea8345cfd7e5b0f1b19d546510cd1ba3a

**Comment by DanCooper** [comment]
Faster than the speed of light :-) Thx!

**Comment by Naliath** [comment]
Let me know if it gives you any trouble. Now it is aligned with the property on the movies object so I don't expect an issue

**Comment by DanCooper** [comment]
Any release date for a new NuGet package with this fix? :-)

**Comment by LordMike** [comment]
Not yet. A lot of changes will happen.
I can make a pre-release though?

**Comment by DanCooper** [comment]
That will be great. That's the only bug in your TMDB API that crashes our software. All other issues can be handled.

**Comment by LordMike** [comment]
I'll see to it then.

**Comment by LordMike** [comment]
@DanCooper 
I haven't done much testing on this (I just compiled `master` in release mode)
https://www.nuget.org/packages/TMDbLib/0.9.0.1-alpha

I should probably run the test suite.. :P

**Comment by LordMike** [comment]
@DanCooper I ran the test suite and all looked good. `0.9.0.1-alpha` _should_ be stable.

**Comment by DanCooper** [comment]
I've installed the package 2min after it was on Nuget :-) and it works great for me, many thanks.

New alpha version of Ember Media Manager is released and looks like it works for all users.
