### ISSUE TITLE
How to get popular movies

### ISSUE THREAD

**Issue by zmhtike** [LordMike/TMDbLib#183]
I need some advice please. I am trying to use discover to get popular movies as follow:

DiscoverMovie popular = client.DiscoverMovies().OrderBy(DiscoverMovieSortBy.PopularityDesc);

I do not get any result. I think it is not right. Could you show me how to use Discover to get popular movie list. Thanks alot!!!

**Comment by zmhtike** [comment]
I found GetMovieList that can get popular movies. But I still want to know how to use DiscoverMovie class.  Thanks.

**Comment by LordMike** [comment]
Oh, I just noticed why. You're not completing the query using `Query()`.
The `DiscoverMovie` class is just a wrapper around a query.

Example:

    SearchContainer<SearchMovie> result = client.DiscoverMovies().OrderBy(DiscoverMovieSortBy.PopularityDesc).Query().Result;
