### ISSUE TITLE
SearchTv type

### ISSUE THREAD

**Issue by tidusjar** [LordMike/TMDbLib#184]
It seems that the type `SearchTv` is missing some information e.g. `overview`.

Looking at the code it seems to be there but it is not included in my assembly (0.8.3.0 from Nuget) 
Why is this?

**Comment by LordMike** [comment]
Reg. the version stuff, it may have been added later on. A "blame" for the file (https://github.com/LordMike/TMDbLib/commit/b5ac0dd8d1a17eda6a7d1212f36667abeef98b65) shows that I added that specific field in July last year.

On the NuGet page, you can see that the 0.8.3 package is not the latest (albeit latest "stable"). So try out f.ex. https://www.nuget.org/packages/TMDbLib/0.8.6-alpha or even more daringly the 0.9 version.

**Comment by tidusjar** [comment]
Thanks,

I downloaded and compiled the master solution and added the assembly. Changed it all to async/await methods and the tasks was not completing (faulted status). Then I used 0.9 and everything works fine. Strange!
Great library. If you need any work done is be happy to contribute.
