### ISSUE TITLE
crash if TVSeason.ExternalIds.TvrageId is not an integer

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#185]
Found a new bug with `ExternalIds.TvrageId`. Looks like it can also be a `String` and not only Integer.

TMDB API Result of The Simpsons, Season 1:
`"external_ids":{"freebase_mid":"/m/0cmqz_","freebase_id":"/en/the_simpsons_season_1","tvdb_id":"2727","tvrage_id":"/the-simpsons/episode_list/1"`

It's little bit confusing, TMDB displays 0 on [website](https://www.themoviedb.org/tv/456-the-simpsons/season/1/edit?active_nav_item=external_ids&language=en), but the upper string in [API result](http://api.themoviedb.org/3/tv/456/season/1?append_to_response=external_ids&api_key=c6b31d1cdad6a56a23f0c913e2482a31).

**Comment by Naliath** [comment]
fixed  44a3e4a
