### ISSUE TITLE
Will you support CoreCLR?

### ISSUE THREAD

**Issue by agoretsky** [LordMike/TMDbLib#188]
Do you have any plans to porting TMDbLib over CoreCLR?

**Comment by Naliath** [comment]
If the PCL version ever sees the light of day it should be usable from Core libraries

**Comment by LordMike** [comment]
It seems something is broken with replying by email. Here's what I wrote on the 16th.

Well. The ground work was laid but then a larger project started at work… and now I’m stuck in spain with a festival coming up in the next few weeks…
 
We removed the restsharp integration and “rolled our own”. That removed the #1 reason not to go core.
 
Can we do a core/PCL without having more than one project and still be usable from both PCL and regular?

**Comment by jensenkd** [comment]
I can't wait for this!  Is there any reason why it wouldn't compile to .net core now that restsharp is gone?

**Comment by Naliath** [comment]
For reference, we might need 2 versions: A core lib and a PCL lib (regular). As I understand it should work but might not atm. MS releases 2 versions of all their stuff as well atm a regular version and a core version

https://github.com/aspnet/Home/issues/1356.

**Comment by LordMike** [comment]
I've been working a little with Core projects for a few days now, and decided to give TMDbLib a go.
I've created a Core library project, and copied over all the TMDbLib files. I've then added `net45` as a framework in addition to `netcoreapp1.0` .. so far so good.

Then I've fixed the compile issues (minor things) - all good.

VS builds two libraries for me on compile (present in `bin\Debug\net45` and `bin\Debug\netcoreapp1.0`) - all good.

I should now be able to make a Nuget package with two targets - so that when you install it for core projects and regular projects alike, it'll choose the correct one.

**Comment by jensenkd** [comment]
Boom! Sweet music to my ears Mike.

**Comment by LordMike** [comment]
@jensenkd I have some issues though. I suspect they're purely IDE related: I cannot keep the Tests and the TestApplication in .NET 4.5 and reference the new Core project. A number of issues crop up on Google related to referencing `xproj` from `csproj`.

I suspect it's purely cosmetic (VS/MsBuild picks the wrong build), as I can reference the compiled assemblies just fine.

**Comment by LordMike** [comment]
@jensenkd try:

`Install-Package TMDbLib -Version 0.9.1.1-alpha -Pre`

**Comment by Naliath** [comment]
Cool that you got it working in one nuget. Wonder why they made 2 packages for the MS dotnet stuff, possibly the source that is different enough?

**Comment by LordMike** [comment]
I have no idea what I did. They built the tool for me (thank god - I feared the Nuget part)..

I'm currently working on Tests - almost nailed it. (Had to rewrite all tests to xUnit - so I've just done a lot of replaces ...)

**Comment by LordMike** [comment]
@jensenkd Fixed a few issues with Core and upgraded Newtonsoft: `Install-Package TMDbLib -Version 0.9.1.2-alpha -Pre`

@Naliath Now tests are working and migrated to Core.
