### ISSUE TITLE
GetChangesMoviesAsync() Needs to return "Adult = null" not "false"

### ISSUE THREAD

**Issue by Lynk5** [LordMike/TMDbLib#189]
Hi !

After verification with the TMDB API support, the intended behaviour of this method is to return updates/changes operated on movies. In order to indicate that a movie has been deleted, one may use the flag "Adult=null" which is automatically converted to false in the Wrapper.

I updated the code locally by just removing the : "[JsonConverter(typeof(TmdbNullBoolAsFalse))]" attribute and changing the DTO related field to a Nullable (bool?).

The reason why they called this flag "Adult" is still a mystery to me ;).

I'm not yet a contributor for this project and just wanted to rise up the issue.

It's a good C# Wrapper overall that I just started to use and am enjoying very much.

All the best!

Lynk5

**Comment by LordMike** [comment]
Oh god. Not that boolean again... :/

Could you link to the API discussion?
I'll make the adult field nullable then.

**Comment by Lynk5** [comment]
Sure !

Here is the link toward the TMDB forum post : https://www.themoviedb.org/talk/57613344c3a36808aa001497

Moreover, do you intend to use the Inversion of Control (IoC) pattern and therefore create interfaces that would allow creating stubs of the C# API for local testing ?

Regards

Lynk5
