### ISSUE TITLE
SearchMovie return the IMDB Id?

### ISSUE THREAD

**Issue by tidusjar** [LordMike/TMDbLib#196]
Hi, 

Is it possible to include the IMDB Id in the result of `SearchMovie()` ? 

It currently returns type `SearchContainer<SearchMovie>` and `SearchMovie` doesn't contain the IMDB id, but if we looked up an individual movie using `GetMovie` the results contain an imdb id.

Referenced issue: https://github.com/tidusjar/PlexRequests.Net/issues/400

**Comment by LordMike** [comment]
Hi. Could you check if the TMDb docs mention an IMDB Id?

We most likely don't include it because they don't provide it.

**Comment by tidusjar** [comment]
Good point. They don't provide it. Awesome Lib though! Using it in PlexRequests.Net!

**Comment by LordMike** [comment]
Cool. Let me know if there are any issues with the library. I know there may be some inconsistencies with f.ex. thrown exceptions or method names.
