### ISSUE TITLE
UWP platform

### ISSUE THREAD

**Issue by Tar4s** [LordMike/TMDbLib#198]
Can you migrate this API to UWP platform? It will be great!

**Comment by LordMike** [comment]
I can't see why not .. I'll try to figure out what the moniker for UWP is.

**Comment by LordMike** [comment]
@Tar4s could you check out `0.9.6.0-alpha` on Nuget?

**Comment by Tar4s** [comment]
@LordMike course! one moment

**Comment by Tar4s** [comment]
@LordMike Everything connects perfectly! But unfortunately, I use bindings. So, i must working with classes and fields marked as [DataMember] and [DataContract]. JsonProperty does not work with bindings. My program in XAML doesn't see necessary classes, and i can't compile the code :(

**Comment by LordMike** [comment]
This is if you're sending the TMDbLib objects over your WCF channels as just that - objects, right?

I *could* mark everything with DataMember and DataContract - but is this a good idea?

**Comment by Tar4s** [comment]
@LordMike I can't say for sure, because I'm not familiar with all the subtleties. For the experiment, can you mark SearchMovie class only, which I need.

**Comment by LordMike** [comment]
But is it because of WCF? For an experiment, you could fetch the code and compile yourself - adding the attributes as needed.

**Comment by Naliath** [comment]
Should not matter for us. It does not affect our flow


Get Outlook for Android






On Thu, Aug 11, 2016 at 8:30 PM +0200, "Michael Bisbjerg" <notifications@github.com> wrote:





But is it because of WCF? For an experiment, you could fetch the code and compile yourself - adding the attributes as needed.

**Comment by LordMike** [comment]
I'm worried about referencing the Serialization primitives. From what I gather, they're not even available on all platforms, so in the worst case we end up with a huge bunch of #ifdef's.. And then I'd just rather not.

**Comment by Naliath** [comment]
Valid point, @Tar4s I sugest wrapping the objects in your own dto's where needed and use something like automapper to transition between the 2 domains. This would also allow you to add things like INotifyPropertyChanged and such

**Comment by Tar4s** [comment]
@LordMike now I see. support
@Naliath understood. will look for
thanks to all

**Comment by LordMike** [comment]
Or, if you don't want to use AutoMapper, use the existing Newtonsoft.Json and simply Serialize what we give you, and then deserialize into your own DTO's.

Closing.
