### ISSUE TITLE
Handle Requests through a Proxy

### ISSUE THREAD

**Issue by lersouza** [LordMike/TMDbLib#201]
In .NET Core, to handle request through a proxy you must set a custom HttpRequestHandler and set the proxy property. One could check this here: [https://github.com/dotnet/corefx/issues/7037].

As it is encapsulated in the TMDbClient class, it is not possible to configure proxy manually. A way of doing this would be to check configuration. You could also receive an optional "settings" object in TMDbClient constructor or look into environment variables (like HTTP_PROXY).

**Comment by LordMike** [comment]
I would go the constructor way then. So you can provide the implementation of whatever httpclient can use. 

This should do it?

A pull request setting it up would be appreciated :)

**Comment by lersouza** [comment]
OK. Working on it.
I created the "issue-201-proxy-support" branch locally to work on this. Can it be created in this repo so I can push the code to it?

**Comment by LordMike** [comment]
Normally you fork the project, create whatever branches you want.
Once done, you submit a pull request. :)

Mvh.
Michael

**Comment by lersouza** [comment]
Great. Tks.

**Comment by LordMike** [comment]
@lersouza thanks for the changes. I went through them and made a few minor edits (it also seemed like you never passed the WebProxy to the RestClient).

https://www.nuget.org/packages/TMDbLib/1.0.3-alpha

Ver. `1.0.3-alpha` includes your changes, and I was able to use my local Fiddler as a proxy with your code. :)
