### ISSUE TITLE
Support for Xamarin.iOS

### ISSUE THREAD

**Issue by hrafnl** [LordMike/TMDbLib#204]
I wanted to try TMDbLib with Xamarin.iOS (or Xamarin in general).

When I install the NuGet package, I get the following error:

Could not install package 'System.Net.Http 4.0.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is this something you would like to consider?

**Comment by LordMike** [comment]
Most certainly. Have you tried adding a target to the TMDbLib project.json file?

**Comment by LordMike** [comment]
Correction - it is not directly possible yet. 

https://github.com/dotnet/cli/issues/589

Until it becomes possible to have it built as part of the `dotnet`  suite, it's probably too much effort from my end.. Sadly. A workaround is:

* Include the TMDbLib code and create a project that targets any intended platform.
* Copy out the netstandard1.0 dll from the Nuget package, and reference it directly.

**Comment by ebadola** [comment]
Hi Mike , what is your opinion about using https://github.com/restsharp/RestSharp instate of JSON.NET and  System.Net.Http,
and RestSharp support multiple platform

**Comment by Naliath** [comment]
Not good since that was what we had... had to remove it exactly for compatibility reasons. Should be easy enough to build against a xamarin scope since we can push this as a plc assembly already.

In new terms we should be able to build against the .net standard platform
