### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by evpxregu** [LordMike/TMDbLib#206]
Under what license is this library released?

**Comment by LordMike** [comment]
Hmm. I hadn't thought of that.
Why do you ask?

**Comment by evpxregu** [comment]
I want to use it for a project, and am wondering if  I can legally do so.

**Comment by LordMike** [comment]
@Naliath would you be ok with an MIT license?

**Comment by Naliath** [comment]
Sounds good, it's not like we are doing anything revolutionary here. If it can some someone some time all the power to them

**Comment by evpxregu** [comment]
Thanks guys!
