### ISSUE TITLE
NotImplementedException when serializing SearchMovie object

### ISSUE THREAD

**Issue by Bukran** [LordMike/TMDbLib#207]
Hi there.

I am receiving a NotImplementedException when trying to (Json) serialize a SearchMovie object.
I've noticed the problem comes from method WriteJson (SearchBaseConverter.cs) Is there any reason to leave it this way? Couldn't you just override ReadJson and leave the WriteJson part to the base JsonConverter?

`public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)`
`{`
`throw new NotImplementedException();`
`}`

Thanks in advance.

**Comment by LordMike** [comment]
I kinda should've expected somebody to want to serialize stuff again. I'll look into creating writers for the various converters. 

As for just relaying them to base, I think it might not work - not always at least. The converters should be transitive, meaning that serializing A to B should allow you to deserialize B back to A.

**Comment by LordMike** [comment]
@Bukran I've made a number of changes in this direction. 
You should be able to check it out once I get `1.0.1-alpha` up.

**Comment by Bukran** [comment]
That's great news @LordMike.
My team will really appreciate this promptness, thanks ;)

**Comment by LordMike** [comment]
I found a number of issues when serializing certain types. So not all converters will be able to be converted. Not yet at least. 

Did this alpha edition resolve your issue? (I assume it did since you closed the issue)

**Comment by Bukran** [comment]
It did, indeed @LordMike. Thanks.
I didn't noticed 1.0.1-alpha was already up and was just waiting for the next major update.
I have already tried `SearchMovie` and `Movie` classes and they both serialize ok.

**Comment by LordMike** [comment]
Great :)

Merry Christmas.
