### ISSUE TITLE
Page 1001 error 

### ISSUE THREAD

**Issue by YuqseLx** [LordMike/TMDbLib#208]
Hey thank you for big work for this.
I got error when i want 
await client.DiscoverMoviesAsync().Query(1001);
An error is http://prntscr.com/dne6ec 
But he say when page = 1000
http://prntscr.com/dne6k6

Thanks for reply

**Comment by LordMike** [comment]
Could be a bug on tmdb's end. Could you try directly against tmdb's API?

**Comment by YuqseLx** [comment]
Ah yes it's a limit :/ Thank you
