### ISSUE TITLE
TMDbClient.AccountGetRatedMoviesAsync does not return movie's rating

### ISSUE THREAD

**Issue by irriss** [LordMike/TMDbLib#213]
The method `TMDbClient.AccountGetRatedMoviesAsync` returns object `SearchMovie` which does not contain field `Rating` however corresponding API method returns this field.

**Comment by LordMike** [comment]
Seems to be correct :)
I'll have a fix up shortly.

**Comment by LordMike** [comment]
It's up on Nuget, https://www.nuget.org/packages/TMDbLib/1.0.5-alpha.

Thanks for reporting :)
