### ISSUE TITLE
Always got Null using GetTvSeasonImagesAsync

### ISSUE THREAD

**Issue by SR2k** [LordMike/TMDbLib#216]
I don't know why but `GetTvSeasonImagesAsync` always returns with the property `Poster`=`null`. Yet `GetPersonImagesAsync` works perfectly in the exactly same codes.

```csharp
Debug.WriteLine("Get Season Image Started ---------------");

var BestImg = new ImageData();

try
{
    var season = await client.GetTvSeasonImagesAsync(tmdbId, seasonNum);

    Debug.WriteLine(season.Id);
    // All output is 0

    var i = 0;

    if (season != null && season.Posters != null && season.Posters.Count > 0)
    {
        Debug.WriteLine("Not null");

        // Get the best poster
        foreach (var image in season.Posters)
        {
            if (i == 0 || image.VoteAverage > BestImg.VoteAverage)
            {
                BestImg.VoteAverage = image.VoteAverage;
                BestImg.FilePath = "https://image.tmdb.org/t/p/original" + image.FilePath;
            }
            i++;
        }
    }
    else
    {
        if (season == null)
            Debug.WriteLine("season == null");
        else if (season.Posters == null)
            Debug.WriteLine("season.Poster == null");
            //All output is "season.Poster == null"
        else if (season.Posters.Count <= 0)
            Debug.WriteLine("season.Poster.Count == " + season.Posters.Count);

        BestImg.FilePath = "ms-appdate:///Assets/DefaultPoster.scale-400.png";
    }
}

catch(Exception ex)
{
    Debug.WriteLine(ex.Message);
    BestImg.FilePath = "ms-appdate:///DefaultAssets/Poster.scale-400.png";
}

Debug.WriteLine("Get Season Image Finished ---------------");
return BestImg.FilePath;
```

Output: 
```
Get Season Image Started  ---------------
0
season.Poster == null
Get Season Image Finished  ---------------
```

**Comment by Naliath** [comment]
Yo,

try with this data for me please
int breakingBad = 1396;
in season = 1
PosterImages images = await client.GetTvSeasonImagesAsync(breakingBad, season);

I just tried that and got results no issue using the latest version of the library.

FYI you can use the following to get the full img url:  
Uri imageUri = client.GetImageUrl(size, imageData.FilePath);

This takes into account the urls that are returned from tmdb as part of it's configuration (it might change)

Cheers

**Comment by SR2k** [comment]
Yeah I've got what's going wrong there. I've being using Trakt.tv api to get season info. And it returns the TMDB Id of each seasons but what `GetTvSeasonImagesAsync` needs is the id of the seires. Yhakns a lot 👍

**Comment by Naliath** [comment]
Ok, the seasonId is not really used much in the api. Usually it's simply the seriesid and season number.
