### ISSUE TITLE
Get Recommendations for both movies and tv

### ISSUE THREAD

**Issue by FrederikBolding** [LordMike/TMDbLib#217]
Calls to the "get recommendations" methods seem to be missing or am I misunderstanding something?

https://developers.themoviedb.org/3/movies/get-movie-recommendations
https://developers.themoviedb.org/3/tv/get-tv-recommendations

**Comment by Naliath** [comment]
Did a quick check and this does seem to be something that is missing. I´ll see if I can add it later this week. It will depend largely on how well it fits in the existing object tree.

**Comment by FrederikBolding** [comment]
It seems to be identical or close to the search result JSON :-)

**Comment by Naliath** [comment]
https://github.com/LordMike/TMDbLib/pull/218

should be ok, as soon as @LordMike has a look it can be merged to base and a  new nuget build can be published

**Comment by FrederikBolding** [comment]
Cool, thanks! 😄

**Comment by FrederikBolding** [comment]
@Naliath When do you suspect that the pull request is going to be merged in?

**Comment by Naliath** [comment]
If @LordMike does not get to it today, I'll do so in a few hours. I am not able to push a new nuget through so you will have to pull the branch and build your own.

**Comment by Naliath** [comment]
Nuget should be up to date, let me know how it works out for you. You will need to use the prerelease version
