### ISSUE TITLE
Crash while getting info for "Hercules: The Legendary Journeys"

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#219]
TV Show: "Hercules: The Legendary Journeys"
TMDB ID: 4615

Looks like something is wrong with the data comes from TMDB (something with season number?) while scraping the tv show.

`GetTvShowAsync(4615, TMDbLib.Objects.TvShows.TvShowMethods.ContentRatings Or TMDbLib.Objects.TvShows.TvShowMethods.Credits Or TMDbLib.Objects.TvShows.TvShowMethods.ExternalIds)`

Here is a log of VS:

`bei System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---&amp;gt; System.Reflection.TargetInvocationException: Während des Vorgangs ist eine Ausnahme aufgetreten, sodass das Ergebnis ungültig ist. Weitere Ausnahmedetails finden Sie in InnerException. ---&amp;gt; System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---&amp;gt; Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'seasons[0].season_number', line 1, position 1798. ---&amp;gt; System.InvalidCastException: Das NULL-Objekt kann nicht in einen Werttyp konvertiert werden.`

Also I've issues with these tv shows:
- Highlander
- In Plain sight

**Comment by Naliath** [comment]
for reference:
{
  "backdrop_path": "/yMy0hEckprt3rsXVXJDExKYKOud.jpg",
  "created_by": [
    {
      "id": 1222834,
      "name": "Christian Williams",
      "profile_path": null
    }
  ],
  "episode_run_time": [
    45,
    60
  ],
  "first_air_date": "1995-01-29",
  "genres": [
    {
      "id": 10759,
      "name": "Action & Adventure"
    },
    {
      "id": 18,
      "name": "Drama"
    },
    {
      "id": 10765,
      "name": "Sci-Fi & Fantasy"
    }
  ],
  "homepage": "",
  "id": 4615,
  "in_production": false,
  "languages": [
    "en"
  ],
  "last_air_date": "1999-11-27",
  "name": "Hercules: The Legendary Journeys",
  "networks": [
    {
      "id": 30,
      "name": "USA Network"
    },
    {
      "id": 184,
      "name": "Broadcast syndication"
    }
  ],
  "number_of_episodes": 126,
  "number_of_seasons": 7,
  "origin_country": [
    "US"
  ],
  "original_language": "en",
  "original_name": "Hercules: The Legendary Journeys",
  "overview": "Hercules: The Legendary Journeys is a television series, filmed in New Zealand and the United States. It was produced from 1995, and was very loosely based on the tales of the classical Greek culture hero Heracles. It ran for six seasons, producing action figures and other memorabilia as it became one of the highest rated syndicated television shows in the world at that time. It also gained a cult following along with its spin-off, Xena: Warrior Princess.\n\nIt was preceded by several TV movies with the same major characters in 1994 as part of Universal Television's Action Pack: in order, Hercules and the Amazon Women, Hercules and the Lost Kingdom, Hercules and the Circle of Fire, Hercules in the Underworld, and Hercules in the Maze of the Minotaur, the last of which served mostly as a \"clip show\" of the previous movies as a lead up to the series.",
  "popularity": 1.272883,
  "poster_path": "/ayK0FP2CHrFG8CGDJ1fYgKVa5JP.jpg",
  "production_companies": [
    {
      "name": "Renaissance Pictures",
      "id": 467
    },
    {
      "name": "Pacific Renaissance Pictures Ltd.",
      "id": 7893
    },
    {
      "name": "Universal Television",
      "id": 26727
    },
    {
      "name": "Studios USA Television",
      "id": 35321
    },
    {
      "name": "MCA Television",
      "id": 35869
    }
  ],
  "seasons": [
    {
      "air_date": null,
      "episode_count": 0,
      "id": 14084,
      "poster_path": null,
      "season_number": null
    },
    {
      "air_date": "1994-04-25",
      "episode_count": 56,
      "id": 14091,
      "poster_path": "/MdGsBgahACYHba89cPbMrj5gAd.jpg",
      "season_number": 0
    },
    {
      "air_date": "1995-01-29",
      "episode_count": 13,
      "id": 14085,
      "poster_path": "/oaei0qCs1YKCubzy0ixEi12JIsW.jpg",
      "season_number": 1
    },
    {
      "air_date": "1995-09-04",
      "episode_count": 24,
      "id": 14086,
      "poster_path": "/pt3Nt3VUKaooMzmNiCxF12hWHSN.jpg",
      "season_number": 2
    },
    {
      "air_date": "1996-10-07",
      "episode_count": 28,
      "id": 14087,
      "poster_path": "/rWKVLyXtx7by5OJ8HZdSJ7Knjs9.jpg",
      "season_number": 3
    },
    {
      "air_date": "1997-10-11",
      "episode_count": 29,
      "id": 14088,
      "poster_path": "/9XGAu3Jk3nXTAu0rXpH1I9rdwHu.jpg",
      "season_number": 4
    },
    {
      "air_date": "1998-10-03",
      "episode_count": 24,
      "id": 14089,
      "poster_path": "/dSxMYGzw0A2Th7Dn5iCBVDJzQwG.jpg",
      "season_number": 5
    },
    {
      "air_date": "1999-10-02",
      "episode_count": 8,
      "id": 14090,
      "poster_path": "/vZFqVRerRLE2Bd0zA4xO2NVqwZH.jpg",
      "season_number": 6
    }
  ],
  "status": "Ended",
  "type": "Scripted",
  "vote_average": 6.4,
  "vote_count": 55
}

**Comment by Naliath** [comment]
there is a season with number null, seems like this should not be allowed so I'll send it along to Travis

**Comment by Naliath** [comment]
Data has been fixed so should be OK when the cache clears on the api side. Props to Travis for the quick action

**Comment by LordMike** [comment]
Did Highlander and In Plain Sight fail for the same reasons?

**Comment by Naliath** [comment]
I'll check later, but Travis updated 60 others.

**Comment by LordMike** [comment]
It's probably not a problem anymore then :)
Good job.

**Comment by DanCooper** [comment]
Works now. Thank you for the message to TMDB!
