### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jojoba2010** [LordMike/TMDbLib#221]
ASP.NET MVC :

client.GetMoviePopularListAsync(); Error : Id = 6, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

client.GetConfig(); Error : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by LordMike** [comment]
Works fine here. Both fetching configs (`GetConfig`) and the popular movie list.

The value parsed there ("<") seems like it was HTML. Is it possible you're behind a proxy or are using a different base URL than the default one?

**Comment by LordMike** [comment]
Note that it is entirely possible for this to be a transient error on TMDbs end.

**Comment by jojoba2010** [comment]
Thanks for reply ;
when i use this code in Asp.NET 
client.GetMoviePopularListAsync();
i get  Error :
 Id = 6, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"
but in windowsApp no error

**Comment by LordMike** [comment]
Technically - that's not an error.. It's that the Task hasn't been startet yet.

Note that (almost) all methods on this API are async.
