### ISSUE TITLE
You have exceeded the maximum number of request allowed by TMDb please try again later

### ISSUE THREAD

**Issue by JamesMaxwel** [LordMike/TMDbLib#223]
I have received this error, even waiting for the necessary time.
e.g  
` Dim Client = New TMDbClient("my-api-key")
 Threading.Thread.Sleep(10000) '10 seconds
Dim TvShow = Client.GetTvShowAsync("1399").Result
result in error "You have exceeded the maximum number of request allowed by TMDb please try again later"
`

**Comment by JamesMaxwel** [comment]
I think I found the source of my problem

https://www.themoviedb.org/talk/59a5de3ac3a3684005013b59

**Comment by LordMike** [comment]
Yea. Seems like it :D

What a way to enable IPv6 :D
