### ISSUE TITLE
Discover movies missing region parameter

### ISSUE THREAD

**Issue by fmilioni** [LordMike/TMDbLib#224]
How can I set the region when using the DiscoverMovies API?

This url below gives me about 450 results, but when I use TMDbLib this value goes up to 7800 results.

`https://api.themoviedb.org/3/discover/movie?api_key=xxxx&region=BR&primary_release_date.gte=2017-01-01`

Is the region option available or I'm doing it wrong?

```c#
await tmdbClient.DiscoverMoviesAsync()
      .WherePrimaryReleaseDateIsAfter(new DateTime(2017, 01, 01))
      .Query();

**Comment by Naliath** [comment]
discover is a different endpoint, I only added the region filter to the movie methods. So atm it is not available
