### ISSUE TITLE
Use compression for API calls

### ISSUE THREAD

**Issue by sarathkcm** [LordMike/TMDbLib#225]
Hi,

Thank you for such a comprehensive wrapper for TMDb. I find it very useful.

Would it be possible to set an "Accept-Encoding: gzip" header in the requests, may be as an optionally configurable feature? Sorry if this is already possible, as I couldn't find it documented anywhere.

**Comment by sarathkcm** [comment]
There is a significant reduction in the response size with this header on.

![image](https://user-images.githubusercontent.com/14143311/30183152-fe653fa8-9436-11e7-940a-8b558679f652.png)

**Comment by Naliath** [comment]
I'll take a look this weekend, if you are right there is no reason for us not to use this since the underlying .net component can deal with the unpacking.

Good job spotting it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Naliath** [comment]
from what I can tell the default of the client handler already specifies this so it should be ok...

![image](https://user-images.githubusercontent.com/795462/30238460-6c895908-9548-11e7-9da2-cf90b930d649.png)

**Comment by sarathkcm** [comment]
Interesting!. For me, it's not added by default. 

![image](https://user-images.githubusercontent.com/14143311/30238572-08900018-9567-11e7-8784-3fe1364fa954.png)

**Comment by sarathkcm** [comment]
@Naliath Which version of .NET are you trying in? Could it be something related to [this issue in .NET Core 2](https://github.com/dotnet/corefx/issues/18646)?

**Comment by LordMike** [comment]
Most likely is. As I read it, anything but netcore 1.x will /not/ use gzip by default.

**Comment by Naliath** [comment]
Yea easy enough to set it, I'll throw it on later today. Unless you see any reason not to? I figure purpose of the lib is to get the data as efficiently as possible.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LordMike** [comment]
None at all. Give it a whirl.
Bonus: Have it as an option :)

**Comment by Naliath** [comment]
aight branch with the fix is up so give it a go and check if this fixes it for you since I can't test it for you :)

**Comment by sarathkcm** [comment]
Yup, works. Thanks.
