### ISSUE TITLE
reviewid

### ISSUE THREAD

**Issue by RickySan65** [LordMike/TMDbLib#226]
How do i get a reviewid from a show?

**Comment by RickySan65** [comment]
Thought it found it, but didn't, passing show id to get review data (breaking bad) but nothing shows, any pointers what id to pass to GetReviewAsync?

**Comment by LordMike** [comment]
https://developers.themoviedb.org/3/movies/get-movie-reviews

It would seem you need to pass the movies Id. Any Movie object should contain an Id - is this what you're after?

Note that Movies and Tv have different endpoints/methods - it's entirely possible you cannot get reviews by TV show/episode/ ..

**Comment by RickySan65** [comment]
i think you can't get them for tv shows, which is a bummer, but now it makes sense i'm not getting any data back :)
