### ISSUE TITLE
Downloading posters

### ISSUE THREAD

**Issue by DutchJavaDev** [LordMike/TMDbLib#227]
When i try to download posters from my favorite movie list i cant seem to download some of them like,
Batman v superman dawn of justice and some others, i have tried to get all the poster links for the poster i cant download and all off the links seem to fail for some reason.

**(Came a cross another bug: only applies for the wonder woman poster so far)**
When i download the wonder woman poster i don't get the English poster but in some other language.

**Comment by LordMike** [comment]
Are you successfully getting the image id's and giving them to the image url ... builder?

**Comment by LordMike** [comment]
var mov = client.GetMovieAsync(297762, "en").Result;

            var urlB = client.GetImageUrl(client.Config.Images.PosterSizes.Last(), mov.BackdropPath);
            var urlP = client.GetImageUrl(client.Config.Images.PosterSizes.Last(), mov.PosterPath);

I've tried the above, and I get these two respectively:

* http://image.tmdb.org/t/p/original/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg
* http://image.tmdb.org/t/p/original/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg

.. although it's hard to tell if they're english... I suppose the title is the same in a lot of places :)

**Comment by DutchJavaDev** [comment]
Thanks hacker-man!

When i could not download some posters in the first place i tried to get all the poster links for each movie hoping it would find at least one downloadable image, but instead i got like 35 to 216 failed attempts (WebExceptions) to download one of the posters using .Net WebClient.

Thanks it works now 👍 (Great library)

**Comment by LordMike** [comment]
Do you know where you went wrong?.. I'd be happy to update documentation etc. :)

**Comment by DutchJavaDev** [comment]
This what i was using when i started using the library and to me i thought this should just work,
but i failed like i said above on some movies.

```
var request = client.AccountGetFavoriteMoviesAsync().Result.Result;

foreach(var movie in request)
{
var uri = client.GetImageUrl("w500",movie.PosterPath);
}

```

**Comment by LordMike** [comment]
It's odd.. Given that `w500` is in the list of accepted poster sizes (I assume it is), every poster *should* have that size present.. 

It could be an issue on TMDb's end.

**Comment by Naliath** [comment]
I must say I have had strange issues with posters before. Leave this issue open I will check my own logs and see if I can reproduce your issue and narrow down the possible error. (won't be for a few days though)

**Comment by DutchJavaDev** [comment]
Well after i implemented
 ```
var mov = client.GetMovieAsync(297762, "en").Result;

var urlB = client.GetImageUrl(client.Config.Images.BackdropSizes.Last(), mov.BackdropPath);
var urlP = client.GetImageUrl(client.Config.Images.PosterSizes.Last(), mov.PosterPath);
```
it has been working fine but now a few days later its back again, i think u where wright that it might be on the side of Themoviedb.org.

Here is a list of movies on which my application failed to download the poster's in case you want to try it out. #(These where just to test my Favorite Movies list on Themoviedb.org)#
```
Hellboy II: The Golden Army
Alien: Covenant
Avengers: Age of Ultron
Batman v Superman: Dawn of Justice
Kingsman: The Secret Service
Star Wars: The Force Awakens
Thor: The Dark World
```

**Comment by LordMike** [comment]
I tried just now with Thor (76338):

```
Thor: The Dark World, Backdrop: w300: OK
Thor: The Dark World, Backdrop: w780: OK
Thor: The Dark World, Backdrop: w1280: OK
Thor: The Dark World, Backdrop: original: OK
Thor: The Dark World, Poster: w92: OK
Thor: The Dark World, Poster: w154: OK
Thor: The Dark World, Poster: w185: OK
Thor: The Dark World, Poster: w342: OK
Thor: The Dark World, Poster: w500: OK
Thor: The Dark World, Poster: w780: OK
Thor: The Dark World, Poster: original: OK
```

Avengers (99861)
```
Avengers: Age of Ultron, Backdrop: w300: OK
Avengers: Age of Ultron, Backdrop: w780: OK
Avengers: Age of Ultron, Backdrop: w1280: OK
Avengers: Age of Ultron, Backdrop: original: OK
Avengers: Age of Ultron, Poster: w92: OK
Avengers: Age of Ultron, Poster: w154: OK
Avengers: Age of Ultron, Poster: w185: OK
Avengers: Age of Ultron, Poster: w342: OK
Avengers: Age of Ultron, Poster: w500: OK
Avengers: Age of Ultron, Poster: w780: OK
Avengers: Age of Ultron, Poster: original: OK
```

I'm really not seeing what you are.

Code for reference.

            var mov = client.GetMovieAsync(99861, "en").Result;

            foreach (string size in client.Config.Images.BackdropSizes)
            {
                var url = client.GetImageUrl(size, mov.BackdropPath);
                var resp = new HttpClient().GetAsync(url).Result;

                Console.WriteLine($"{mov.Title}, Backdrop: {size}: {resp.StatusCode}");
            }

            foreach (string size in client.Config.Images.PosterSizes)
            {
                var url = client.GetImageUrl(size, mov.PosterPath);
                var resp = new HttpClient().GetAsync(url).Result;

                Console.WriteLine($"{mov.Title}, Poster: {size}: {resp.StatusCode}");
            }

**Comment by DutchJavaDev** [comment]
I am using this and for some reason it got the error back, might be in my code because i tried the above code before trying to download the poster and i got the same result like you did but when i try to download an poster some of them fail, going to spend a lot of time to figure out why this is happening.
```C#
            using (var web = new WebClient())
            {
                try
                {
                    var movie = _tmDb.GetMovieAsync(item.Id, "en").Result;

                    foreach (var size in _tmDb.Config.Images.PosterSizes)
                    {
                        var uri = _tmDb.GetImageUrl(size, movie.PosterPath);

                        web.DownloadFile(uri, TempDataDirectory + movie.Title);

                        break;
                    }

                    return true;
                }
                catch (Exception e)
                {
                    if ( e is WebException )
                    {
                        Console.WriteLine(e.Message);
                    }
                    return false;
                }
```

**Comment by Naliath** [comment]
just in case you need something to clean the names

        /// <summary>
        /// Removes all invalid characters from a path/file name string and returns the cleaned string value.
        /// All invalid characters are simply removed, no new characters are inserted
        /// </summary>
        /// <param name="path">string to rid of invalid characters</param>
        /// <returns>cleaned string</returns>
        public static string RemoveInvalidCharacters(string path)
        {
            return System.IO.Path.GetInvalidFileNameChars().Aggregate(path, (current, invalidCharacter) => current.Replace(invalidCharacter.ToString(CultureInfo.InvariantCulture), ""));
        }
