### ISSUE TITLE
EventSourceException errors

### ISSUE THREAD

**Issue by hgirma** [LordMike/TMDbLib#229]
Hello, 

I'm seeing a lot of errors similar to the following after making a simple call.

EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "AwaitTaskContinuationScheduled"

for example.

await _tmdbClient.GetTvEpisodeAsync(1005, 1, 1);

**Comment by LordMike** [comment]
That specific query gives an HTTP 404, so that might contribute to any error you're seeing.

I haven't seen those before though. How do you call the methods - in which context?
Could something be messing with the async flow?

**Comment by hgirma** [comment]
sorry, that was just an example

Below is a simulation of what happens in my app, I call it 4 times in rapid succession. Here is what I did, just to make sure there are no threads etc..  I am using VS 2017 15.3.3 (WinForm .NET 4.7)
TMDblib v1.0.0.0

        async void button1_Click(object sender, EventArgs e)
        {
            TMDbClient client = new TMDbClient("key");
            client.GetConfig();
            await client.SearchTvShowAsync("Mad Men");
            await client.GetTvShowAsync(1104);
            await client.GetTvSeasonAsync(1104, 1);
             await client.GetTvEpisodeAsync(1104, 1, 1);
        }

Below is the output in the debugger

EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitBegin"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "AwaitTaskContinuationScheduled"
EventSourceException while processing event "TaskScheduled"
EventSourceException while processing event "TaskStarted"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "TaskWaitEnd"
EventSourceException while processing event "AwaitTaskContinuationScheduled"

**Comment by LordMike** [comment]
Could you try against `1.0.7-alpha` ?

**Comment by hgirma** [comment]
Same result. Were you able to reproduce on your end? It's possible that something is off on my machine, it's a rather strange error without any exception details. It may not be the library at all.

**Comment by LordMike** [comment]
I wasn't. Try looking up the exception type on google.

I did that, and found a bunch of different places where people were talking about it - but there wasn't any concrete indication of why it came as I saw it. You might have a better chance though.
