### ISSUE TITLE
Request tv show and episode by imdbId

### ISSUE THREAD

**Issue by neckaros** [LordMike/TMDbLib#230]
Hello,

as of now for TvShow and Episode we can only send int as id. Therefore we cannot request by imdbId.
It will be great to have the choice like for movies.

Thanks for the great library!

**Comment by Naliath** [comment]
Does the api support this? It did not before, only for movies

**Comment by neckaros** [comment]
You are right! sorry i saw that you were passing imdbid at the same api endpoint for movie and i wrongly assumed it would work for show also.
But i tried it with the api doc and i confirm that it does not work.
Thanks for the quick reply and sorry!

For future reference the recommended solution by Tmdb is to do a search:
```
//Condensed C# that give a SearchTv object
 var show = (await _tmdb.Client.FindAsync(TMDbLib.Objects.Find.FindExternalSource.Imdb, "tt4574334")).TvResults.FirstOrDefault();
```

**Comment by Naliath** [comment]
Np, the movie endpoint using imdb is actually a hidden feature since the spec does not specify it ;)
