### ISSUE TITLE
We could mark objects as Srializable

### ISSUE THREAD

**Issue by amoraitis** [LordMike/TMDbLib#234]
I use this library to search for movies for a bot(BotBuilder), so i need the objects to be serializable.

- [ ] You can asign this to me.

**Comment by LordMike** [comment]
What, like BinarySerializer serializable?

**Comment by amoraitis** [comment]
Like [C#'s serializable](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netframework-4.7.1&viewFallbackFrom=netstandard-1.2)

**Comment by LordMike** [comment]
It's my impression that if I change anything in the models, the serialized objects won't be deserializable ... at least in some form..

https://stackoverflow.com/questions/30240486/how-much-does-a-class-object-have-to-change-in-order-for-binary-deserialization

I can't guarantee the models in any form. Maybe they'll get new fields or miss some, or even change the order of their properties.. Any of these changes could break your storage/transport..

**Comment by LordMike** [comment]
Reading about BotBuilder, it seems that its using it to store state between two messages - is this correct?

If it's ephemeral storage, as in, just temporary storage between two messages - these problems above probably don't apply to you. However, if it's persistently stored on disk for a longer period, you might run into these issues.

**Comment by amoraitis** [comment]
@LordMike Thanks for your time! I will try to create my own requests and classes and deserialize jsons
