### ISSUE TITLE
GetMovieAsync returns empty object

### ISSUE THREAD

**Issue by gabiionut** [LordMike/TMDbLib#235]
When I used `GetMovieAsync ` I noticed that for some movie IDs it returns an empty object.
This is an example: `var movie = client.GetMovieAsync(230).Result;`
Is this methond valid only for some movies or what is the problem ?

**Comment by LordMike** [comment]
That's entirely true. For that specific ID, TMDb returns HTTP 404 - but we parse it anyways.

**Comment by LordMike** [comment]
As a workaround, you can verify that the ID returned is the one you requested - but for now, it's a bug.

**Comment by LordMike** [comment]
Fixed in #275 - error handling has been streamlined, see the new `ThrowApiExceptions` option.
