### ISSUE TITLE
How to get movie genres by id

### ISSUE THREAD

**Issue by Starwer** [LordMike/TMDbLib#237]
Hi,

This question was asked in #154, but the answer didn't fully meet the requirement IMHO, at least not mine.
I just take the snippet from @Max45 at that time:
`SearchContainer result = client.GetMovieList(MovieListType.Popular, "en");`
 `foreach (MovieResult movie in result.Results)`
` {`
`     List data = movie.GenreIds;`
`     var IdGenres = string.Join(",", data);`
`     Console.WriteLine(movie.Title + " --- " + IdGenres);`
` }`

It was suggested to use `GetGenres`. However this is a method of `Movie` Class. What we have here is a `MovieResult`, which doesn't have this method. 

Of course, we could use a `GetMovieAsync` to retrieve the `Movie` object for each `MovieResult` element, but this then requires TMDb requests for every search-result, which is inefficient and much slower, especially with the free license limitation of 40 requests every 10 seconds in TMDb.

So, would there be a Look-Up-Table somewhere, or helper function, to convert these GenreIds to genre identifiers, without further request to TMDb ?

**Comment by LordMike** [comment]
Isn't the `GetMovieGenresAsync` what you're after? (https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/Client/TMDbClientGenres.cs#L36)

It provides `Genre` objects which are Id/Name pairs: https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/Objects/General/Genre.cs

**Comment by Starwer** [comment]
Hi LordMike,

Thanks a lot! This indeed works and fully answer my question.
