### ISSUE TITLE
Collection.Overview isn't decoded

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#238]
Looks like Collection.Overview is not decoded: https://i.imgur.com/MZnVWpr.png

Collection.Name is fine.

**Comment by LordMike** [comment]
I can't immediately find anything where we HTML Encode. So I assume it's HTML Encoded from TMDb's side.

Ugh. That's tough. In principle an API shouldn't return anything-encoded.. @Naliath should we HTML Decode here? What if TMDb changes their ways? - we'll potentially double-decode :O

**Comment by LordMike** [comment]
We do HTMLDecode already in Movies. So we could probably just extend the hack.

https://github.com/LordMike/TMDbLib/blob/856b1584d540c9442d3c921e80ced2b5cf04d83c/TMDbLib/Client/TMDbClientMovies.cs#L128

**Comment by Naliath** [comment]
Perhaps we should report this, it does indeed seem strange that we get that back. The hack is not the worst thing and since we already do it for one, why not the other.

**Comment by DanCooper** [comment]
Check this thread, looks like we have already discussed that:
https://www.themoviedb.org/talk/564ae26bc3a3686031002638

**Comment by LordMike** [comment]
Do the hack.
