### ISSUE TITLE
Keep HttpClient between multiple requests

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#241]
Each HttpClient wil use its own connection pool. In our code, we use each HttpClient once, leading to cases where we may be abusing resources at TMDb and locally.

The HttpClient should be set in the Clients space and then used from there on each request.

**Comment by Hyperz** [comment]
Wouldn't the correct way be to have the TMDbClient constructor take a HttpClient instance? From what I've read there's only supposed to be 1 application-wide instance of HttpClient so in that case it doesn't make sense to have 3rd-party libraries create their own instances. Or am I missing something?

**Comment by Naliath** [comment]
Nah having 1 for the lib is fine. You want one per target, else you risk header colisions and other strange business

**Comment by LordMike** [comment]
Accepting a client from the outside would make sense if we wanted to leave all control of f.ex. handlers and default headers to the caller. But all docs would say "new HttpClient()" (or use defaults, which is a new client), both for simplicity (very few would use the option) - and as @Naliath said, we'd risk all kinds of things.

The main goal of sharing a HttpClient is to maintain persisted connections to a hostname. Each HttpClient instance will have its own pool of connections.
