### ISSUE TITLE
JsonProperty for Job object

### ISSUE THREAD

**Issue by scavarda** [LordMike/TMDbLib#249]
Please check if this is correct

https://github.com/LordMike/TMDbLib/blob/049fba9f720acf21534ae8d2f4dca7a375586cb8/TMDbLib/Objects/General/Job.cs#L11

Shouldn't it be "jobs" instead of "job_list"?

**Comment by LordMike** [comment]
It does look like it should be `jobs` (https://developers.themoviedb.org/3/configuration/get-jobs-1)
