### ISSUE TITLE
TV show "created by" gender is inconsistent

### ISSUE THREAD

**Issue by FrederikBolding** [LordMike/TMDbLib#260]
It's behaving weirdly at the moment. I've opened a thread at TMDb: https://www.themoviedb.org/talk/5a7c5637c3a3680f9400ec04

**Comment by FrederikBolding** [comment]
@LordMike I'm not sure this is ever going to get fixed 😆 We might just need to support genders, as well as null. Which I believe we already do (with the PR).

**Comment by LordMike** [comment]
Probably not.. -.-
