### ISSUE TITLE
Error converting value {null} to type 'System.Int32'

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#269]
I get this error if I try to get the season 1 details with credits in tv show (ID 62264):

`Error converting value {null} to type 'System.Int32'. Path 'credits.crew[0].id', line 1, position 10122.`

Used code:
`GetTvSeasonAsync(62264, 1, TMDbLib.Objects.TvShows.TvSeasonMethods.Credits Or TMDbLib.Objects.TvShows.TvSeasonMethods.ExternalIds)`

On the TMDB API test website no one of the "crew" entries has an ID, so I don't know if that's an issue on TMDB side or not:

```json
{
  "crew": [
    {
      "credit_id": "551ff0129251415c7a0018f0",
      "department": "Production",
      "gender": 1,
      "id": null,
      "job": "Casting",
      "name": "Lauren Grey",
      "profile_path": null
    },
    {
      "credit_id": "551ff0529251415c87001939",
      "department": "Directing",
      "gender": 2,
      "id": null,
      "job": "Director",
      "name": "Sam Raimi",
      "profile_path": "/uEAaCUJzyMI8N5mOVyLtaOPKoEf.jpg"
    }
  ],
  "id": 65657
}
```

**Comment by LordMike** [comment]
Seems like a TMDb issue. I would expect these objects to always have an ID.

**Comment by DanCooper** [comment]
Ok, then a will add a new ticket to the TMDB API support.

**Comment by DanCooper** [comment]
Oh, just seen that there already is one: https://www.themoviedb.org/talk/5ad886080e0a264330010bbd

Thx, I think you can close this one.

**Comment by LordMike** [comment]
According to the API documentation, every single thing in that response is optional...

![image](https://user-images.githubusercontent.com/1027111/39008252-72f5652e-4408-11e8-820d-59c0f259f7e2.png)

**Comment by LordMike** [comment]
Oh i see.. "or null". Right. Wonder what the optional thing means.

**Comment by DanCooper** [comment]
No idea why all fiields are optional. But the ID can only be "integer" and it's "null" in my case. Looks like a new issue, never get this before.

**Comment by LordMike** [comment]
Seems like the three other guys in the thread have all been hit just now. Could be general thing.

**Comment by LordMike** [comment]
@DanCooper see update on TMDb Talk.
