### ISSUE TITLE
Possible Omissions?

### ISSUE THREAD

**Issue by Afy65** [LordMike/TMDbLib#273]
Hi please do correct me if I'm wrong :)

Should `GetNetworkAsync` in TVShows? not return the following?
https://developers.themoviedb.org/3/networks/get-network-details

Also these two methods seem to be missing as well for Networks?
https://developers.themoviedb.org/3/networks/get-network-alternative-names
https://developers.themoviedb.org/3/networks/get-network-images

Love the work you have done - works a treat :)

Kind regards

Daniel

**Comment by LordMike** [comment]
They might be - if you're missing anything, you're more than welcome to submit PR's for it.

**Comment by FrederikBolding** [comment]
Added a PR for it 😄

**Comment by FrederikBolding** [comment]
This can be closed when #274 has been merged.
