### ISSUE TITLE
TVShow 

### ISSUE THREAD

**Issue by LeagueOfAimtec** [LordMike/TMDbLib#277]
Can you help me about C# codes of these acoording to your library ?
I want to get these data of TV Shows:

Name
Year
Number of episodes
Genres
Network
Summary
Poster
Number of Sesons
Name of Episode
Released time of Episode
Summary of Episode
Which season and which episode number
Rating episode and tv show

**Comment by LordMike** [comment]
You should be able to do something similar to whats on the front-page for Movies, for TV Shows.

```
TMDbClient client = new TMDbClient("APIKey");
Movie movie = client.GetMovie(47964, MovieMethods.Casts | MovieMethods.Trailers);
```

Use the GetTvShow and similar methods.
