### ISSUE TITLE
How to get ?

### ISSUE THREAD

**Issue by LeagueOfAimtec** [LordMike/TMDbLib#278]
How to get genres of TVShow and how to get all names of episodes in particular season.

**Comment by LordMike** [comment]
You'll have to go explore the API. We pretty much one-to-one map the official API docs, found here https://developers.themoviedb.org/3.

Find what you need in there, and then go to our client and find the relevant methods.

**Comment by LeagueOfAimtec** [comment]
You are not helpfull

**Comment by Naliath** [comment]
The info is there, it simply requires some effort on your part. There are examples in the test project and the unit tests if you need code examples

**Comment by LordMike** [comment]
Most of the library can be explored by using Intellisense in Visual Studio for example. Code completion on f.ex. the client will show you all the methods we have, most of them are self-explanatory.

Simply writing `client.Tv` should show you stuff like `GetTvShow`.
