### ISSUE TITLE
Add the ability to search trending movies

### ISSUE THREAD

**Issue by jason2li** [LordMike/TMDbLib#286]
I love this project, but it would really help if we could get the trending movies.

**Comment by FrederikBolding** [comment]
Thanks for the report - I can add this whenever I have time (within a day or two) 😄

**Comment by jason2li** [comment]
That would be great!  Thanks so much!

**Comment by LordMike** [comment]
Allternatively, @jason2li, submitting a PR is always the fastest way to add new features :)

**Comment by FrederikBolding** [comment]
Haha, yes, indeed @LordMike 😆

**Comment by LordMike** [comment]
@jason2li @FrederikBolding  was kind enough to provider a PR. Could you pull this code and try it out, alternatively I'll try to get to making an Alpha release later today.
