### ISSUE TITLE
Question about DiscoverMovies

### ISSUE THREAD

**Issue by neven10** [LordMike/TMDbLib#289]
When using Discover Movies methods   like this : 
       
            var client = new TMDbClient("apiKey");
            var dc = new  
            DiscoverMovie(client).IncludeAdultMovies(false).WhereVoteAverageIsAtLeast( something random);            
            SearchContainer<SearchMovie> results = await dc.Query(page);

how do i get max page beforehand ? Is that possible?

**Comment by FrederikBolding** [comment]
You have to do at least one request to get the total pages. It should be included in the response for every request :-)
