### ISSUE TITLE
Async HELP

### ISSUE THREAD

**Issue by codirx** [LordMike/TMDbLib#292]
Hello I am new at async programming in c#. Can you transform this method to async like download all tv show informations, images  at the same time. Note: USCSerie = User control to display tv show poster,name,date etc

        public static List<USCSerie> GetSeries(List<int>serieIDs, string language)
        {
            WebClient wc = new WebClient();
            List<USCSerie> SerieList = new List<USCSerie>();
            USCSerie serieUSC;
            foreach (var serieID in serieIDs)
            {
                serieUSC = new USCSerie();
                var tvShow = client.GetTvShowAsync(serieID, TvShowMethods.Images, language).Result;
                serieUSC.TxtSerieName.Text = tvShow.OriginalName;
                serieUSC.TxtSerieAirDate.Text = tvShow.FirstAirDate.Value.Year.ToString();
                string genreNames = "";
                foreach (var genre in tvShow.Genres)
                {
                    genreNames += genre.Name;
                }
                serieUSC.TxtSerieGenre.Text = genreNames;
                string fileName = tvShow.PosterPath;
                fileName = fileName.Replace("/", "adf");
                fileName = fileName.Replace(".", "ah");
                client.GetConfig();
                if (File.Exists(pathPoster + fileName))
                {
                    var bitmap = new Bitmap(pathPoster + fileName);
                    GetPosterFromFile(bitmap, serieUSC.SerieImage);
                }
                else
                {
                    Uri url = client.GetImageUrl(client.Config.Images.PosterSizes.Last(), tvShow.PosterPath);
                    byte[] imageData = wc.DownloadData(url);
                    File.WriteAllBytes(pathPoster + fileName, imageData);
                    var bitmap = new Bitmap(pathPoster + fileName);
                    GetPosterFromFile(bitmap, serieUSC.SerieImage);
                }
                serieUSC.Name = string.Format("Serie{0}", serieID);
                SerieList.Add(serieUSC);
            }
            return SerieList;
        }

      

        [DllImport("gdi32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern bool DeleteObject(IntPtr value);
        public static void GetPosterFromFile(Bitmap bitmap, System.Windows.Controls.Image ImageSerie)
        {
            IntPtr bmpPt = bitmap.GetHbitmap();
            BitmapSource bitmapSource =
                System.Windows.Interop.Imaging.CreateBitmapSourceFromHBitmap(
                    bmpPt,
                    IntPtr.Zero,
                    Int32Rect.Empty,
                    BitmapSizeOptions.FromEmptyOptions());
            ImageSerie.Source = bitmapSource;
            bitmapSource.Freeze();
            DeleteObject(bmpPt);
        }`

**Comment by LordMike** [comment]
We're not a dedicated programming how-to.. But you'll want to look into stuff like `Parallel.ForEach` and the `async/await` patterns.
