### ISSUE TITLE
null Id's in GetChangesTvAsync response

### ISSUE THREAD

**Issue by rpm61** [LordMike/TMDbLib#296]
I got a null Id on a single page of the response from GetChangesTvAsync which killed the method. Wondering if you've seen this and if maybe Id should be nullable in ChangesListItem?

**Comment by LordMike** [comment]
Which arguments did you provide?

**Comment by rpm61** [comment]
I am getting the total pages first, then looping through by page with

var TvChanges = client.GetChangesTvAsync(i, startDate, endDate).Result;

where i is the page number. My start date is 11/22/2018, enddate 11/30/2018. I get an error on page 16 today (Yesterday it was oage 11):

JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'results[96].id', line 1, position 2593.

**Comment by LordMike** [comment]
Ok. This is likely a case where TMDb has messed up their data again. Would you, @rpm61, be able to get the original JSON for that request?

Using a proxy like Fiddler will easily let you see all requests as they are made, and then you can grab the response body for the offending request. We can then send this to TMDb.

**Comment by rpm61** [comment]
Will do, I'm working on another issue right now, but I will get this to you today.

Thank you very much for your help.

**Comment by rpm61** [comment]
There is a null value on line 32 here. I have run this several times and the null will appear on different pages, though it seems to move further back, higher page number, as time goes on. This time it is on page 17.

`{
"results": [
{
"id": 4564,
"adult": false
},
{
"id": 6618,
"adult": false
},
{
"id": 77960,
"adult": false
},
{
"id": 84515,
"adult": false
},
{
"id": 79492,
"adult": false
},
{
"id": 81951,
"adult": false
},
{
"id": 31628,
"adult": false
},
{
"id": null,
"adult": null
},
{
"id": 62689,
"adult": false
},
{
"id": 70220,
"adult": false
},
{
"id": 69753,
"adult": false
},
{
"id": 17442,
"adult": false
},
{
"id": 83129,
"adult": false
},
{
"id": 83634,
"adult": false
},
{
"id": 83548,
"adult": false
},
{
"id": 72736,
"adult": false
},
{
"id": 84275,
"adult": false
},
{
"id": 37508,
"adult": false
},
{
"id": 75127,
"adult": false
},
{
"id": 53787,
"adult": false
},
{
"id": 2440,
"adult": false
},
{
"id": 84301,
"adult": false
},
{
"id": 83238,
"adult": false
},
{
"id": 58520,
"adult": false
},
{
"id": 83314,
"adult": false
},
{
"id": 62715,
"adult": false
},
{
"id": 43020,
"adult": false
},
{
"id": 60802,
"adult": false
},
{
"id": 13897,
"adult": false
},
{
"id": 48873,
"adult": false
},
{
"id": 81747,
"adult": false
},
{
"id": 61374,
"adult": false
},
{
"id": 83836,
"adult": false
},
{
"id": 74024,
"adult": false
},
{
"id": 83821,
"adult": false
},
{
"id": 80411,
"adult": false
},
{
"id": 1798,
"adult": false
},
{
"id": 83602,
"adult": false
},
{
"id": 77707,
"adult": false
},
{
"id": 61222,
"adult": false
},
{
"id": 31974,
"adult": false
},
{
"id": 33901,
"adult": false
},
{
"id": 83745,
"adult": false
},
{
"id": 67098,
"adult": false
},
{
"id": 33507,
"adult": false
},
{
"id": 19531,
"adult": false
},
{
"id": 80671,
"adult": false
},
{
"id": 39255,
"adult": false
},
{
"id": 363,
"adult": false
},
{
"id": 84389,
"adult": false
},
{
"id": 5194,
"adult": false
},
{
"id": 3909,
"adult": false
},
{
"id": 84353,
"adult": false
},
{
"id": 84358,
"adult": false
},
{
"id": 70699,
"adult": true
},
{
"id": 5895,
"adult": false
},
{
"id": 82428,
"adult": false
},
{
"id": 84290,
"adult": false
},
{
"id": 994,
"adult": false
},
{
"id": 84292,
"adult": false
},
{
"id": 82875,
"adult": false
},
{
"id": 84011,
"adult": false
},
{
"id": 2472,
"adult": false
},
{
"id": 55931,
"adult": false
},
{
"id": 81018,
"adult": false
},
{
"id": 76059,
"adult": false
},
{
"id": 2852,
"adult": false
},
{
"id": 69221,
"adult": false
},
{
"id": 83265,
"adult": false
},
{
"id": 39373,
"adult": false
},
{
"id": 34379,
"adult": false
},
{
"id": 61740,
"adult": false
},
{
"id": 4917,
"adult": false
},
{
"id": 6971,
"adult": false
},
{
"id": 4493,
"adult": false
},
{
"id": 66645,
"adult": false
},
{
"id": 50,
"adult": false
},
{
"id": 60863,
"adult": false
},
{
"id": 51643,
"adult": false
},
{
"id": 84306,
"adult": true
},
{
"id": 12971,
"adult": false
},
{
"id": 82122,
"adult": false
},
{
"id": 83545,
"adult": false
},
{
"id": 84279,
"adult": false
},
{
"id": 12727,
"adult": false
},
{
"id": 81496,
"adult": false
},
{
"id": 33996,
"adult": false
},
{
"id": 83440,
"adult": false
},
{
"id": 10545,
"adult": true
},
{
"id": 83109,
"adult": false
},
{
"id": 75379,
"adult": false
},
{
"id": 17404,
"adult": false
},
{
"id": 46879,
"adult": false
},
{
"id": 66830,
"adult": false
},
{
"id": 53069,
"adult": false
},
{
"id": 81548,
"adult": false
},
{
"id": 84304,
"adult": false
},
{
"id": 81772,
"adult": false
},
{
"id": 82879,
"adult": false
},
{
"id": 55724,
"adult": false
}
],
"page": 17,
"total_pages": 18,
"total_results": 1745
}`

**Comment by FrederikBolding** [comment]
@LordMike We should probably consider a solution in which we throw these values out or simply ignore the fact that they're null?

**Comment by LordMike** [comment]
... if we don't just ignore it, wait for TMDb to fix it, and then all be happy :P

**Comment by LordMike** [comment]
https://www.themoviedb.org/talk/5c0014ddc3a36869ae05f8ef

**Comment by rpm61** [comment]
My 2¢ -
It would be nice to see this handled, since even if they fix this one it  will likely happen again. I also like the int? as I stated earlier, and let consuming processes discard the nulls. Your converter works just as well for me, but the int? is easier and I don't see that as an unreasonable hardship, but maybe some would.

**Comment by LordMike** [comment]
If we went down that road, the library would make no promises, and pretty much everything you'd see would need a `if (obj.Value.HasValue) doStuff(obj.Value.Value)` ... which I'd really dislike. 

I'd rather handle that crap in the library itself... The converter is one way.

**Comment by rpm61** [comment]
I agree, though I guess I am looking at this as feeling the use case for the changes is likely the same for all. Get the Ids with changes, loop through them and update, so no problem checking them as you go or removing before the loop. I get your point though, and I certainly wouldn't mind being assured of no nulls.
Btw, I found a null in the movie changes today as well.

**Comment by LordMike** [comment]
Oh yay.

**Comment by LordMike** [comment]
@rpm61 can you try out the latest code?

If it works, I'll push it to nuget

**Comment by rpm61** [comment]
Thanks, I'll do that today and let you know.

**Comment by rpm61** [comment]
This worked. I confirmed there is still a null Id on page 17 of my results so all looks good, thank you very much.
I have been assuming these changes include new records, records with changes and deleted records, but I haven't been able to confirm this from TMDb docs. Do you know if that is correct?

**Comment by LordMike** [comment]
I'm really not sure. The Changes API is something I've never worked with in depth.

**Comment by LordMike** [comment]
If TMDb responds on the Changes thing, we can change stuff here. Else, use `1.3.2-alpha`, @rpm61.

Thanks for troubleshooting for us :)

**Comment by Naliath** [comment]
Just fyi the changes api is not super reliable I often have changes not comming in and have to do a full refresh once in a while...
