### ISSUE TITLE
Proper disposing of client

### ISSUE THREAD

**Issue by takoz53** [LordMike/TMDbLib#304]
Hi there,

In the code, there is a client?.Dispose(); function, but I can't call it apparently, so how is the proper way to Dispose the client on a shutdown of the Application? Is the NuGet / Library not up to date or how comes its undisposable?

Thank you.

**Comment by LordMike** [comment]
`TMDbClient` directly inherits from `IDisposable` and the `void Dispose()` is public. 

You can't call `myClient.Dispose();` ?

**Comment by takoz53** [comment]
I checked that it inherits from that, but I can not call it. I don't remember where I downloaded the DLL from but It shouldn't be outdated since I downloaded it just a month ago. Was the Dispose() function implemented just recently? I'm using this: https://puu.sh/DoFQ5/aaa2d23ed6.dll and the code is as follows:

![devenv_rMQcVaD8Xi](https://user-images.githubusercontent.com/16865864/57245583-83e95880-703b-11e9-8dae-d84ece022f59.png)

**Comment by Naliath** [comment]
Strange but you do not need to call it explicitly anyway. Just let .net do the cleanup

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by takoz53** [comment]
@Naliath so the issue here is my friend shuts down his problem and then the application is still running in the background, so I assumed there might be an issue while disposing. Maybe its not working properly, I'm not sure. So we wanted to implement the Disposing and test it whether it works. .Net ain't doing le cleanup properly I think.

**Comment by Naliath** [comment]
Very strange, try just setting reference to the client to null and forcing garbage collection. https://stackoverflow.com/q/4257372/7937082

Just to see if that clears up the issue. I have been using the library for a very long time and never had issues like this with it.

You could also check with a memory profiler like dotMemory what is going on.

**Comment by takoz53** [comment]
@Naliath I'm unsure how to use dotMemory so I won't be able to figure out what's going on probably. I can try to force.

So to do is:
`client = null;
GC.Collect();`, correct?

**Comment by LordMike** [comment]
@takoz53 you're running `1.0.0`, so you could say that `Dispose` has been implemented "recently". Please install `1.3.2-alpha`.

It probably shouldn't have been alpha for so long :O
