### ISSUE TITLE
SerializeObject

### ISSUE THREAD

**Issue by alxbrn** [LordMike/TMDbLib#305]
Hello,
Just real quick i love the project, nice job.

I'm attempting to JsonConvert.SerializeObject a List of type "TMDbLib.Objects.Movies.Movie", but whenever i try to do so i get this error: System.NotImplementedException: 'The method or operation is not implemented.'.

Is there some way to do this in the library without me having to write it out or am i doing something wrong?

**Comment by FrederikBolding** [comment]
Hi!

I just tested it myself and was able to serialize a list of Movie objects. It seems that issue is somehow on your end.

Are you using the latest version?

**Comment by LordMike** [comment]
@alxbrn you're probably running an old version. The converters we had were previously read-only, so serializing yourself would invoke the not implemented exception.

**Comment by alxbrn** [comment]
I attempted the same code with the latest "alpha" and everything worked fine.
