### ISSUE TITLE
Genre_ids issue with similar tv shows

### ISSUE THREAD

**Issue by FrederikBolding** [LordMike/TMDbLib#307]
The genre_ids field is sometimes returned as {} for empty instead of []. 

This can't be deserialized by TMDb lib.

For example:

https://api.themoviedb.org/3/tv/76534?api_key=%APIKEY%&language=en-US&append_to_response=similar

**Comment by FrederikBolding** [comment]
Posted about it here: https://www.themoviedb.org/talk/5d3d880721621b0012f11f4c

**Comment by LordMike** [comment]
Must be fixed locally - in b9ff10cc510ce4c5dfdd1c5a768eb42237bd55f3 I added a converter for this kind of thing. I've added a new commit which annotates _all_ `genre_ids` with this converter. 

They also reference this issue for tracking.
