### ISSUE TITLE
External IDs

### ISSUE THREAD

**Issue by causio** [LordMike/TMDbLib#311]
Movies support external_ids, but the MovieMethods param for GetMovie doesn't include that as an option. Additionally, Tv external_ids has facebook_id, twitter_id, instagram_id, but those aren't on the ExternalIdsTvShow class. Would be very helpful to get all of those data points.

**Comment by FrederikBolding** [comment]
This is all available in the latest prelease version here: https://www.nuget.org/packages/TMDbLib/1.4.0-alpha
