### ISSUE TITLE
If Year parameter is added in SearchMovieAsync the api does not return any results

### ISSUE THREAD

**Issue by sdesyllas** [LordMike/TMDbLib#312]
await client.SearchMovieAsync(title, language, 1, false, year) : returns no results

await client.SearchMovieAsync(title, language, 1, false) : returns results with no problem

Even when I use the api directly outside of C# I still get no results if I add year in the url

https://api.themoviedb.org/3/search/movie?api_key=xxxx&language=en&query=Cars&page=1&include_adult=false&year=2006
(no results)

https://api.themoviedb.org/3/search/movie?api_key=xxxx&language=en&query=Cars&page=1&include_adult=false
(get results)

**Comment by FrederikBolding** [comment]
Seems to be an API issue. 

Create a thread here to let them know: https://www.themoviedb.org/talk/category/5047958519c29526b50017d6

Also, might be related to this: https://www.themoviedb.org/talk/5d545ed4b76cbb0013d828d8

**Comment by sdesyllas** [comment]
Thanks for the quick response @FrederikBolding 
You are right, this seems more of a tmdb rest api issue rather than the nuget package issue

I created a [thread ](https://www.themoviedb.org/talk/5d553e334bc38b195524353f) as you suggested

**Comment by LordMike** [comment]
I think our implementation is correct, so I'll just go ahead and close this as it's fully external.

Great work, @FrederikBolding.
