### ISSUE TITLE
Discover Movie Release Date

### ISSUE THREAD

**Issue by BostonSlikk** [LordMike/TMDbLib#313]
Am trying to do this in VN. Net but whenever I try to use discover where the primary date is after a date and also before a date, it doesn't return same results if I do it manually in web browser using the filter parameters.

I've imported everything and am using the alpha 1.40 but here's what I'm doing (first result is a movie that's 8 years before the year I'm using) 

Dim client As New TmdbClient(xxxxx) 
Dim dm As DiscoverMovie
Dim res As New SearchContainer (Of SearchMovie)

dm = client. DiscoverMovieAsync()
dm.WherePrimaryReleaseDateIsAfter(new DateTime (2014, 9, 15))
dm.WherePrimaryReleaseDateIsBefore(new DateTime(2014, 10, 22))
dm.OrderBy(DiscoverMovieSortBy. PopularityDesc)
res = dm.Query().Result
For Each prop In Res.Results
Msgbox (prop.Title)
Next

Those are the dates they use on their api documentation discover examples of themoviedb website. First results should be John Wick, Equalizer, then Fury... This code returns Cars, John Wick, Guardians of the Galaxy. Cars was released in 2006.  Am I doing something wrong because when I do it raw using System.Net and make the Http request and deserialize the json, it returns the movies in order the way it should. Thanks for any help you can provide.

**Comment by BostonSlikk** [comment]
Oh, I wanted to mention that it does seem to work correctly if I drop the "Primary" from the "WherePrimaryReleaseDateIsBefore" to just "WhereReleaseDateIsBefore" but keep the WherePrimaryReleaseDateIsAfter in tact.

**Comment by LordMike** [comment]
It's not guaranteed that the order of movies on the website will be identical to the one provided by the API. It's likely, but not guaranteed.

Also. As you've found, there are two release dates to search by. The primary is defined as;

> Filter and only include movies that have a primary release date that is greater or equal to the specified value. 

.. while the non-primary is: 

> Filter and only include movies that have a release date (looking at all release dates) that is greater or equal to the specified value.

So by using the non-primary, you're filtering by _any_ release date for the movie.
