### ISSUE TITLE
Country in GetMovieNowPlayingListAsync and GetMovieNowPlayingListAsync

### ISSUE THREAD

**Issue by ketnic** [LordMike/TMDbLib#316]
Is there a way to specify a country in GetMovieNowPlayingListAsync and GetMovieNowPlayingListAsync? In #222 it says that it's possible, but I can only add language and page in the method in my program. Is this option now removed or am I missing something?
![1](https://user-images.githubusercontent.com/55064000/64551777-67309a80-d325-11e9-962f-fcde93cbbeeb.png)

**Comment by FrederikBolding** [comment]
Seems like you aren't using the latest version which does have it 😄 You need to use the pre-release version here: https://www.nuget.org/packages/TMDbLib/1.4.0-alpha

@LordMike Maybe, we should stop using pre-release as it seems to cause quite a lot of confusion?

**Comment by ketnic** [comment]
Thanks a lot!
