### ISSUE TITLE
GET /person/popular method is missing

### ISSUE THREAD

**Issue by omeryanar** [LordMike/TMDbLib#323]
Wrapper doesn't include tihs method:

https://developers.themoviedb.org/3/people/get-popular-people

**Comment by FrederikBolding** [comment]
Use `GetPersonListAsync` with `Popular`.

**Comment by omeryanar** [comment]
I saw that method but I thought it was something else because it returns a different class, PersonResult instead of SearchPerson. Now I looked at the properties of this class and they are exactly the same as SearchPerson. So, I think PersonResult class is unnecessary and GetPersonListAsync method should return SearchPerson class instead. By doing so, it will be consistent with movie and tv list methods.

**Comment by FrederikBolding** [comment]
Feel free to open pull requests, if you see ways to improve and fix things!
