### ISSUE TITLE
Several Tv Show methods are missing

### ISSUE THREAD

**Issue by omeryanar** [LordMike/TMDbLib#324]
Wrapper doesn't include following methods:

https://developers.themoviedb.org/3/tv/get-tv-airing-today

https://developers.themoviedb.org/3/tv/get-tv-on-the-air

**Comment by FrederikBolding** [comment]
They are in fact. Use `GetTvShowListAsync` with `OnTheAir` or `AiringToday`.

**Comment by omeryanar** [comment]
I didn't realize that methods, thank you. I thought there are seperate methods for each list, like movie methods: GetMovieUpcomingListAsync, GetMovieNowPlayingListAsync, etc.
For consistency, I think it is a good idea to make an enum for movie methods, too.

**Comment by LordMike** [comment]
We could make a few extension methods for that kind of stuff, although we'll be adding to a very large list of methods. :/
