### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by DenisAndrei** [LordMike/TMDbLib#325]
hello, how can i search  for trending movies?

**Comment by FrederikBolding** [comment]
Maybe something like `GetTrendingMoviesAsync`?

**Comment by DenisAndrei** [comment]
yes, but idk with what to assign it.
here it works like that:
 Movie movie = client.GetMovie(47964, MovieMethods.Casts | MovieMethods.Trailers);
how to do it for GetTrendingMoviesAsync?

**Comment by LordMike** [comment]
Maybe something like `SearchContainer<SearchMovie> trending = client.GetTrendingMoviesAsync(TimeWindow.Week).GetAwaiter().GetResult()` ?

**Comment by DenisAndrei** [comment]
Yes, thank you very much. I have tried that also but without the GetAwaiter() Method.

**Comment by LordMike** [comment]
You need to look up how to do `async` code if you want to use the method without the GetAwaiter(). 

I'm closing this now.
