### ISSUE TITLE
cant access person info

### ISSUE THREAD

**Issue by DenisAndrei** [LordMike/TMDbLib#329]
"Person person1 = client.GetPersonAsync(ID, PersonMethods.Images | PersonMethods.MovieCredits).Result" dont work
ID is correct but when i run the code i get no response

**Comment by DenisAndrei** [comment]
@LordMike @FrederikBolding  some help please. should i change something?

**Comment by LordMike** [comment]
Could you test the API manually, using f.ex. Fiddler or the online client (on the dev docs)?

**Comment by DenisAndrei** [comment]
@LordMike  its working on the online client

**Comment by DenisAndrei** [comment]
@LordMike is this code the way in which the information must be extracted?

**Comment by DenisAndrei** [comment]
@LordMike :D

**Comment by LordMike** [comment]
Which ID are you working with?

**Comment by DenisAndrei** [comment]
any tmdb ID for person  i use dont work

**Comment by DenisAndrei** [comment]
my code just freeze when it's getting to this line

**Comment by LordMike** [comment]
![image](https://user-images.githubusercontent.com/1027111/69996034-84a28880-1551-11ea-9a13-a3037a3eab82.png)

Works fine here.

**Comment by DenisAndrei** [comment]
So what i did wrong in my code?
even if i start a new app and try the code its not working 
"Person person1 = client.GetPersonAsync(1253360, PersonMethods.Images | PersonMethods.MovieCredits).Result"

**Comment by DenisAndrei** [comment]
it freezes and does not go on the next line

**Comment by LordMike** [comment]
Sounds like async issues. I won't be able to troubleshoot it for you, but try running your main method as `static async Task Main(string[] args)`.

Then you can await the call instead of using `.Result`.

```csharp
static async Task Main(string[] args)
{
  TMDbClient client = new TMDbClient("..key..");

  var p1 = await client.GetPersonAsync(1253360);

  Console.WriteLine(p1.Name);
}
```

**Comment by DenisAndrei** [comment]
thanks , its working like that
