### ISSUE TITLE
Have you asked for the Crew information?

### ISSUE THREAD

**Issue by DenisAndrei** [LordMike/TMDbLib#330]
Have you asked for the Crew information?

Many query methods accept an enum indicating extra info to get.

_Originally posted by @LordMike in https://github.com/LordMike/TMDbLib/issues/327#issuecomment-554589858_

**Comment by DenisAndrei** [comment]
I dont know, some of them works with foreach(....)
what other enums?

**Comment by LordMike** [comment]
Example code, please? :)

Also. Try the online client (tmdb docs) and see if you get any details at all.

**Comment by DenisAndrei** [comment]
I tried now and it doesn't work here either
https://developers.themoviedb.org/3/tv/get-tv-credits

**Comment by FrederikBolding** [comment]
If it doesn't work in the UI, it's a question for TMDb 😄

**Comment by DenisAndrei** [comment]
You are right :)
