### ISSUE TITLE
How can i access the next page of trending tvshows

### ISSUE THREAD

**Issue by DenisAndrei** [LordMike/TMDbLib#332]
I do this 
SearchContainer<SearchTv> t = client.GetTrendingTvAsync(TimeWindow.Week).Result
but i cant find a way to get the next page with this method

**Comment by LordMike** [comment]
I'd say you cant:

https://developers.themoviedb.org/3/trending/get-trending

Page is not a parameter on that, unlike f.ex. popular people:

https://developers.themoviedb.org/3/people/get-popular-people

**Comment by DenisAndrei** [comment]
thanks for the clarifications
