### ISSUE TITLE
How can i access the next page of trending tvshows?

### ISSUE THREAD

**Issue by hims889** [LordMike/TMDbLib#335]
Hi ,

i want to access the next page of trending tvshows but there is no parameter defined.
I checked this issue #332 , you said there is no option for this but if we append the page=2 at end we can access the second page as following url.

https://api.themoviedb.org/3/trending/tv/week?api_key=<yourapiKey>&page=2.

Can you provide option for this?

Thanks

**Comment by LordMike** [comment]
Looking at it again, I see the page parameter in the response object.. But surely, if it works, we need to include it.. :)

**Comment by hims889** [comment]
Yes, it is working fine. We can include the parameter :)

Thanks
