### ISSUE TITLE
How to get random movie from a genre

### ISSUE THREAD

**Issue by AndyRaphael** [LordMike/TMDbLib#336]
Is it possible to get a random movie id when searching by genre? I am able to use the DiscoverMoviesAsync() function, but it only returns the first 20 results. I would like to get a random movie. If I use results.Results[randomresult].Title (where randomresult is an integer less than total results, i am only able to get the first 20.

Thanks in advance!

**Comment by Dendraspis** [comment]
Have you tried `GetGenreMoviesAsync()` which takes `includeAllMovies` as a parameter?

**Comment by AndyRaphael** [comment]
It says that function is depreciated, but even then, the foreach loop only shows the first 20 results.  What i am trying to achieve is get a random movie from one or more categories.
Appreciate the help!

**Comment by LordMike** [comment]
There is also this: https://developers.themoviedb.org/3/getting-started/daily-file-exports

You could pick any id from there, and look it up on the API.

**Comment by LordMike** [comment]
I also can't find the docs for `includeAllMovies`, so it's truly deprecated.

In order to get a random movie from the servers database, you'll need a function specifically for that. Any Discover or GetGenreList thingy will be sorted by _something_.. f.ex. their Id's or names. Once they are that, you can only get the same movies, no matter how many times you ask.

The file I linked to should contain everything TMDb has, so using that _you_ will be able to pick random stuff.

**Comment by AndyRaphael** [comment]
Do you know why I am only able to see the first 20 results? I can check total results and that number is much higher. So when trying to get something like results.Results[20].Title will fail, since only index 0 to 19 are allowed. Shouldn't there be indexes for each result that was found?

**Comment by LordMike** [comment]
The results will typically be paged. You can't get all data in one go, that would put too much pressure on the server and take too long to download.

**Comment by AndyRaphael** [comment]
That makes sense. Please forgive my lack of knowledge. I do see that (in my example) there are 53 pages. How would I retrieve the next page?

**Comment by Dendraspis** [comment]
All those functions should have an `int page` parameter where you can specify the page number.
So you can use two random values to select a page and one of those 20 entries.
