### ISSUE TITLE
Missing some optional parameters in SearchTvShowAsync()

### ISSUE THREAD

**Issue by 1970633640** [LordMike/TMDbLib#337]
language
include_adult
**first_air_date_year**

Though I don't think there are "adult" shows in tmdb, but **first_air_date_year** is useful because some tv shows have the same name, such as https://www.themoviedb.org/tv/60735-the-flash (newer) and https://www.themoviedb.org/tv/236-the-flash (older). But when naming the video files, newer ones have the year data in the file name such as ```The.Flash.2014.S06E04.…….mkv```. So I guess that optional parameter is useful when auto reading some TV show files.

**Comment by LordMike** [comment]
Makes sense.
