### ISSUE TITLE
tagline is missing from TvShow Object

### ISSUE THREAD

**Issue by SirSparkles** [LordMike/TMDbLib#349]
Firstly thanks very much for a great library - so easy to use.

I can't find the tagline property in the TVShow object. Am I missing something?

Do we just need 

[JsonProperty("tagline")]
public string Tagline { get; set; }

in https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/Objects/TvShows/TvShow.cs

based on https://developers.themoviedb.org/3/tv/get-tv-details

**Comment by LordMike** [comment]
Certainly seems like it. The changelog also mentions watch/providers api's.

**Comment by wwarby** [comment]
I've actioned this in #355
