### ISSUE TITLE
blazor http client doesn't support proxy

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [LordMike/TMDbLib#354]
```
public RestClient(Uri baseUrl, JsonSerializer serializer, IWebProxy proxy = null)
        {
            BaseUrl = baseUrl;
            Serializer = serializer;
            DefaultQueryString = new List<KeyValuePair<string, string>>();

            MaxRetryCount = 0;
            Proxy = proxy;

            HttpClient = new HttpClient(new HttpClientHandler
            {
                Proxy = proxy // can you delete this? it will be helpful
            });
        }
```

**Comment by INTERNALINTERFERENCE** [comment]
TMDbLib.RestClient is setting the Proxy property to a value (even if it's null). That will throw the [exception](https://github.com/dotnet/runtime/blob/75ae527a90c28effc47df1faf4dda48d86b8f980/src/libraries/System.Net.Http/src/System/Net/Http/BrowserHttpHandler/BrowserHttpHandler.cs#L78)

**Comment by sapr9x3** [comment]
The properly way is not to delete it, but add a little check.

`
public RestClient(Uri baseUrl, JsonSerializer serializer, IWebProxy proxy = null)
{
    BaseUrl = baseUrl;
    Serializer = serializer;
    DefaultQueryString = new List<KeyValuePair<string, string>>();

    MaxRetryCount = 0;
    Proxy = proxy;

    var httpClientHandler = new HttpClientHandler;
    if (proxy != null)
    {
        httpClientHandler.Proxy = proxy;
    }
    HttpClient = new HttpClient(httpClientHandler);
}
`

**Comment by INTERNALINTERFERENCE** [comment]
can u update the library? I wanna use it

**Comment by LordMike** [comment]
Check out 1.7.5-alpha momentarily.
