### ISSUE TITLE
How do I get runtime/length of the movie with DiscoverMoviesAsync ?

### ISSUE THREAD

**Issue by JuhaW** [LordMike/TMDbLib#377]
I got your TMDbLib to work with Visual Studio 2019 VB.Net Winforms.
I just want to drop some short "movies" like Breakdowns of 1936 and so on where actors are not acting in the same movie.

**Comment by LordMike** [comment]
As you can see here: https://developers.themoviedb.org/3/discover/movie-discover

The discover API does not provide runtimes.

You can get this info with `GetMovieAsync(id)` for each move you find via. Discover.
