### ISSUE TITLE
Implement rate limiting

### ISSUE THREAD

**Issue by Naliath** [LordMike/TMDbLib#38]
Add an automatic request throttling setting and if not enabled throw an exception the utilizing application can use to manange it themself
.
ref:http://www.themoviedb.org/talk/5317af69c3a3685c4a0003b1

**Comment by LordMike** [comment]
The feature is now live.

https://www.themoviedb.org/talk/5317af69c3a3685c4a0003b1?page=1

**Comment by Naliath** [comment]
https://github.com/LordMike/TMDbLib/commit/ea8c2e1603fd98baa6bd887fe01405bcd884c094

**Comment by LordMike** [comment]
Added test 6b47d825e34c7bc6b61c7b201d768bd2fb5149f1
