### ISSUE TITLE
V1.8.1 GetTvShowChangesAsync returns a JToken in TMDbLib.Objects.Changes.ChangesContainer

### ISSUE THREAD

**Issue by mpfc75** [LordMike/TMDbLib#380]
I'm trying to work with GetTvShowChangesAsync which returns a TMDbLib.Objects.Changes.ChangesContainer.  Drilling down to the Item list there is a Value field of type JToken. I am having difficulty accessing the data in it.  Should this be a JToken or something else?

**Comment by mpfc75** [comment]
It seems that GetTvSeasonChangesAsync and GetTvEpisodeChangesAsync responses also contain JTokens.

**Comment by mpfc75** [comment]
Looking at it further, is there a way to pass the optional start and end dates, or the page?

**Comment by LordMike** [comment]
As I recall, I made those values JTokens as I can't say anything about their contents. Iirc, the contents correspond to the actual change that was made, f.ex. when adding it could be the values that were added etc.

The value is a Newtonsoft JToken, so you could make your own object if you know what to expect, and convert to it like `.Value.ToObject<MyObject>()`. You can also inspect the Json document programmatically or convert it to a string representation like `.Value.ToString()`.

As for pagination - there [are both start, end and page parameters](https://github.com/LordMike/TMDbLib/blob/2d3d2d4c301951691c4c3d069612fb3db79cdf6a/TMDbLib/Client/TMDbClientChanges.cs#L97-L101).

**Comment by mpfc75** [comment]
Part of my struggle is that I'm not seeing .Value available to me.  Here is a sample snippet.  As you can see, I can have Action, Id, Iso_639_1, and Time.  But the JToken fields OriginalValue and Value appear inaccessible. 
![image](https://user-images.githubusercontent.com/47704863/124369000-23fb9600-dc35-11eb-8a3c-717ac993a987.png)

Regarding start, end, and page... I see them on the Season and Episode change methods, but they aren't on the Show method.
https://developers.themoviedb.org/3/tv/get-tv-changes

Thanks!

**Comment by LordMike** [comment]
I've created this example that shows how it can be used. I still can't say anything about the value, hence it being an `object`, which depends on what the serializer (by default Newtonsoft.Json) decides to use. This is the JToken you see.

I can also see where your confusion comes from. The `ChangeItemBase` is an abstract type. In your screenshot, you're inspecting a `ChangeItemUpdated`. The example below uses type matching to show all types.

```csharp
var changes = await client.GetMovieChangesAsync(848533);

// Example serialization back to json
var json = TMDbJsonSerializer.Instance.SerializeToString(changes);

foreach (var change in changes)
{
    Console.WriteLine("Key: " + change.Key);
    foreach (ChangeItemBase item in change.Items)
    {
        Console.WriteLine(" - Id: " + item.Id);
        switch (item)
        {
            case ChangeItemAdded changeItemAdded:
                Console.WriteLine("   Added: " + changeItemAdded.Value);
                break;
            case ChangeItemCreated changeItemCreated:
                Console.WriteLine("   Created");
                break;
            case ChangeItemDeleted changeItemDeleted:
                Console.WriteLine("   Deleted: " + changeItemDeleted.OriginalValue);
                break;
            case ChangeItemDestroyed changeItemDestroyed:
                Console.WriteLine("   Destroyed: " + changeItemDestroyed.Value);
                break;
            case ChangeItemUpdated changeItemUpdated:
                Console.WriteLine("   Updated: " + changeItemUpdated.OriginalValue + " => " + changeItemUpdated.Value);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(item));
        }
    }

    Console.WriteLine();
}
```

![image](https://user-images.githubusercontent.com/1027111/124804614-ca5bda00-df5a-11eb-822e-352e5ecc9f56.png)

**Comment by mpfc75** [comment]
Thanks for your reply.  
`GetMovieChangesAsync` returns `Task<IList<Change>>`
`GetTvShowChangesAsync` returns `Task<ChangesContainer>`

Your sample (thank you for it) works for Movies, but not for TVShows.

**Comment by LordMike** [comment]
I see that. The four methods could all have been of one or the other type, this is just inconcistency. I've created #381.

The sample should be the same, albeit with minor modifications. The ChangesContainer wraps a `List<Change>`, which in turn has the `ChangeItemBase` which the sample works on.

I can also see the mismatch of parameters in those methods, it could be that a lot of methods are like this. So if you're up for it, you can try adding some of these parameters - f.ex. just for the TV Shows Client. I've created #382 for this.

Mike.

**Comment by mpfc75** [comment]
I've made an update for both #381 and #382.  Let me know what you think.

Stephen
