### ISSUE TITLE
Problem retrieving tagged images of media_type 'episode'

### ISSUE THREAD

**Issue by wickedhanzo** [LordMike/TMDbLib#384]
When retrieving TaggedImages for a person, there is an 'ArgumentOutOfRangeException' for a lot of people.
The problem is that the media_type for these problematic tagged images is 'episode', while only 'tv' and 'movie' is supported in the code (TaggedImageConverter).

An example-json for this kind of tagged image: (person is Tom Hanks (tmdbid 31))

`{
   "aspect_ratio":1.777777777777778,
   "file_path":"/zOfyeSOWa5SPPs82lszeNrMUzH9.jpg",
   "height":1080,
   "id":"574e9546c3a3687ff1001ba0",
   "iso_639_1":null,
   "vote_average":0.0,
   "vote_count":0,
   "width":1920,
   "image_type":"still",
   "media":{
      "air_date":"2016-05-31",
      "episode_number":1,
      "id":1196876,
      "name":"Jimmy Fallon \u0026 Miley Cyrus",
      "overview":"Maya Rudolph and Martin Short star with Kenan Thompson and special guests Miley Cyrus, Larry David, Jimmy Fallon and Tom Hanks.",
      "production_code":"",
      "season_number":1,
      "show_id":66623,
      "still_path":"/4pNDfeyqkqkOhTmebvg46aoqaxP.jpg",
      "vote_average":0.0,
      "vote_count":0
   },
   "media_type":"episode"
}`

**Comment by LordMike** [comment]
Ooh neat, we'll have to add that.. Could you do a PR?
