### ISSUE TITLE
Out of date reviews

### ISSUE THREAD

**Issue by wickedhanzo** [LordMike/TMDbLib#385]
On November 14, 2020  they added an author_details field to the default response, which includes an avatar_path and rating value.
(https://developers.themoviedb.org/3/reviews/get-review-details)

Could these fields be added?

**Comment by LordMike** [comment]
The fastest way is if you're able to a PR for it :)

**Comment by wickedhanzo** [comment]
Made a PR for it (first one I ever made). Feel free to tell me if there's something wrong.
