### ISSUE TITLE
Request for a new release version

### ISSUE THREAD

**Issue by Shadowghost** [LordMike/TMDbLib#396]
We're currently in preparation for releasing [Jellyfin](https://github.com/jellyfin/jellyfin) 10.8 and since we're using TMDbLib it'd be great if we could get in a current release of your library. There were some neat fixes merged since the last library release we'd like to make use of.

We would greatly appreciate if you could check out the currently open PRs and cut a release.

**Comment by LordMike** [comment]
I've followed up on PR's and pushed out `v1.9.0`.

Good luck on your release :).
