### ISSUE TITLE
1.9.0: Can't make TMDbClient requests

### ISSUE THREAD

**Issue by angyanmark** [LordMike/TMDbLib#398]
In the new 1.9.0 release I can't make any request.

Reproduction:
```csharp
TMDbClient client = new TMDbClient("api_key");
Movie movie = await client.GetMovieAsync(11);
```

Every request throws a `System.ObjectDisposedException`.
The `TestApplication` project also fails.

**Comment by NilixMaster** [comment]
I also receive a similar message:
```
Dim T As New TMDbClient("ba238334e47a7cf38fc5d83979dbf84c", True)
Dim res As SearchContainer(Of SearchMovie) = T.SearchMovieAsync("Searchtext").Result
```
Error-Message:
One or more errors occurred. (Cannot access a disposed object. Object name: 'System.Net.Http.HttpConnectionResponseContent'.)

**Comment by LordMike** [comment]
Well - that was unprofessional...

**Comment by LordMike** [comment]
A last minute using should probably have been tested better. I'm pushing `v1.9.1` shortly.

**Comment by angyanmark** [comment]
`1.9.1` works fine, thanks 👌
