### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#4]
Interpret the errors that TMDb produces, and handle them accordingly.
Possibly throw exceptions (and implement Try- methods for 'performance').

**Comment by DanCooper** [comment]
Hi Mike

any news on this? My app crash every time I use a wrong TMDB ID. I've not found a way to handle that without Try/Catch.

**Comment by DanCooper** [comment]
Ok, i think it crash only if someone use long instead of int32 as TMDB ID.

**Comment by LordMike** [comment]
Hi. No. This is a very long-ago thing.
Have you found the root cause for your crash?

If you post a stack trace and/or a method + inputs, I or possibly @Naliath can help you debug.

-----Original Message-----

**Comment by DanCooper** [comment]
Yes, the issue was that i have tried a random number like "317132489468768487".
Maybe it was a little tooooo long for an integer ;-)
Ignore what I said, it's all ok, it was my fault.

**Comment by LordMike** [comment]
In general you should catch exceptions, as we in any case will be unable to handle network level issues.

-----Original Message-----
