### ISSUE TITLE
Test API key

### ISSUE THREAD

**Issue by foxi69** [LordMike/TMDbLib#417]
Hi,

Is there anyway to test the api key is valid in code?

**Comment by LordMike** [comment]
You could always call `AccountGetDetailsAsync`. If this fails somehow, then the API key probably isn't valid.

You should get an `UnauthorizedAccessException` if it wasn't valid (versus a timeout or any other issue that might be)

**Comment by LordMike** [comment]
Maybe the `GetConfig` calls then?
