### ISSUE TITLE
DiscoverMovie missing 'with_release_type' parameter

### ISSUE THREAD

**Issue by bvanderw** [LordMike/TMDbLib#422]
DiscoverMovie is missing the 'with_release_type' parameter.

Probably something like this would work:

```    
public static DiscoverMovie IncludeReleaseTypes(IEnumerable<ReleaseDateType> releaseTypes)
{
   Parameters["with_release_type"] = string.Join("|", releaseTypes.Select(r => ((int)r).ToString()));
   return this;
}
```

**Comment by LordMike** [comment]
I don't understand [this option](https://developers.themoviedb.org/3/discover/movie-discover). If I put in `1,2,3` what does that mean?..
