### ISSUE TITLE
Updated TranslationData model in Nuget Package

### ISSUE THREAD

**Issue by ruben0909** [LordMike/TMDbLib#425]
Hi,

When we could have a new package in Nuget with this PR https://github.com/LordMike/TMDbLib/pull/408 ?

Current version is 1.9.2, and is not working.
I tried to download the package from 
https://nuget.pkg.github.com/LordMike/index.json and https://api.nuget.org/v3/index.json
And it doesn´t work, but when I build code directly it works fine.

Thank you

**Comment by LordMike** [comment]
I've marked the latest as 2.0.0 (because of breaking changes), it should be available soon.
