### ISSUE TITLE
Split TvSeason object in two

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#43]
We might need a `TvSeasonLight` object which only contains the information given by the `GetTvShow()` call. The only information given is: `AirDate`, `Season` and `PosterPath`.

The `GetTvSeason()` method returns a `TvSeason` object, which contains all the fields populated (as the API provides the data).

See #42 for core issue.

**Comment by Naliath** [comment]
This has been changed, the GetTvShow method return a great deal more that the info mentioned above. All in all I think this issue is outdated and can be closed

**Comment by LordMike** [comment]
Fair enough :)
