### ISSUE TITLE
GetTvEpisode not returning any images

### ISSUE THREAD

**Issue by Dreamcooled** [LordMike/TMDbLib#56]
While GetTvShow and GetTvSeason are perfectly fine, GetTvEpisode is not returning any images when passing TvEpisodeMethods.Images as argument.

Corresponding API Page: http://docs.themoviedb.apiary.io/#reference/tv-episodes/tvidseasonseasonnumberepisodeepisodenumber

I think the problem is that the API response contains only a "stills" key for the images and no "backdrops" and "posters" keys.

TMdb 0.7.7 (nuget)

**Comment by LordMike** [comment]
I'm unsure on the original intent, as @Naliath coded up this piece.
However, I've altered the TvEpisode object a bit to account for the StillImages.
