### ISSUE TITLE
TV Show content_ratings

### ISSUE THREAD

**Issue by Duder29** [LordMike/TMDbLib#57]
Maybe I am missing something, but I think we are missing /tv/{id}/content_ratings.
I ultimately want the tv shows rating (ex. TV-MA)
Do we need another MovieMethod? 
Thank you for your work!

**Comment by Naliath** [comment]
This is something that seems relativly new. It's going to be an additional method that needs to be added to the tv show this. Shouldn't be too much work, I'll see if I can make some time for it tomorrow or in the weekend.

**Comment by Naliath** [comment]
added the new call and a few others to the wrapper

**Comment by Duder29** [comment]
Thank you very much!
