### ISSUE TITLE
RestSharp invalid version

### ISSUE THREAD

**Issue by scboffspring** [LordMike/TMDbLib#59]
Hi !

In the last release, apparently the RestSharp dependency does not specify which version to use. RestSharp was updated, and therefore I have an error :

 Could not load file or assembly 'RestSharp, Version=104.4.0.0, Culture=neutral, PublicKeyToken=null' 

I would recomment either to specify the verison in the nuspec file, or setting the "Specific version" settings to false

Regards,

**Comment by LordMike** [comment]
I should really make another Nuget package soon.
