### ISSUE TITLE
Trailer in Differnt languges

### ISSUE THREAD

**Issue by yte424** [LordMike/TMDbLib#61]
Hi, 
I have an issue with getting trailer in different languages. I tried  

    client.DefaultLanguage = "de";
    var trailers = client.GetMovieTrailers(Id);

But I am only getting  the English language trailer. 

The Trailer itself are empty when requesting the movie in another language via      

    client.DefaultLanguage = "de";
    Movie myMovie = client.GetMovie(Id);

Do I do something wrong? I looked it up in the code but I couldn't find the correct position.

Thanks in advance!

**Comment by LordMike** [comment]
Are you certain the movie in question has a german-specific trailer?
Also, if you wish to receive more data using the GetMovie call, than just the basic info, you need to add another parameter. The parameter should specify that you wish to receive Trailer data.

**Comment by yte424** [comment]
Thanks, now it works. I am using parameters for getting more info. Sorry, for not checking more deeply the api.

**Comment by LordMike** [comment]
:)
