### ISSUE TITLE
Missing original_language /movie/{id}

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#64]
IMDB's API get results have it as shown in JSON as:
 
"imdb_id": "tt0137523",
  "original_language": "en",
  "original_title": "Fight Club"

Any change it can be added to the wrapper available from Nuget. I don't code in C or I'd have a go myself. I'm a bit old school and code in VB/VB.net. I looked at your source movie objects and see not reference to "original_language". Did I miss something?
thx 
Joe

**Comment by LordMike** [comment]
You seem to be correct. Looking through the Apiary docs I can see the two extra fields you mention (language and title). It should be as simple as adding them to the Movie object.

**Comment by LordMike** [comment]
I found we missed another field "Video", albeit I have no idea what it means.
It's been committed.
