### ISSUE TITLE
I found we missed another field "Video" [/movie/id]

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#65]
Hi Lordmike;

I put a request it at TMDB for a explanation of this response item. I'll let you know if and what I get an answer from Travis et al (and others).

Regards; Joe

**Comment by LordMike** [comment]
Related: #64

**Comment by joebob49** [comment]
Hi LordMike;

I found some more missing items in /Discovery parameters. I'll review these and post my findings here. Should be today sometime.
Regards; Joe

**Comment by joebob49** [comment]
Lordmike;

looks like a number of changes in TMDB's /discovery There appears to be a number of new?  parameter options yours does not encompass. I have not checked your expected responses against theirs but I would surmise that these may have changed also due to the new parameters (i.e.  "with_cast").

regards; Joe

**Comment by joebob49** [comment]
Hi Lordmike;

Found what TMDB means by video(s). This sure looks like a reference to where or not they have any trailers, teasers, etc. for the movie.

Joe

**Comment by Naliath** [comment]
Missing parameters in the discovery feature are not that surprising, I just quickly added that in and at the time the api wasn't final yet.

**Comment by joebob49** [comment]
Hi Naliath;

Thanks for the info. Any Changes these changes may be showing up in the Nuget release anytime soon? Travis's immediate an future API changes not withstanding. It's holding up some filtering options I'm working on. As I don't code in C I have not idea how to recompile the wrapper.

FYI - I'm coding a personal desktop app in vb/vb.net which is coming along nicely. It has some code which I am willing to share with others. Is it possible to open a forum here to cover using your wrapper in VB into which I can post examples and documentation? I'm willing to moderate the forum so you are not encumbered with more work. 

Regards; Joe

**Comment by joebob49** [comment]
Hi Guys:

I have the true answer to "videos: true/false":

"The Video property is a relatively new field. It "helps us differentiate types of content that aren't truly movies". Some examples are: compilation DVDs, "best of" DVDs, fitness videos, compilation of children's programming, etc. This is an example: SpongeBob Squarepants - Christmas . It's a compilation of Christmas themed episodes from the TV show; not a real movie. These types of entries used to be deleted which upset many people so the video field was added and they are now allowed in the database with their Video field set to "yes".

Regards: Joe

**Comment by LordMike** [comment]
@joebob49 see https://www.nuget.org/packages/TMDbLib/0.8.1-alpha
