### ISSUE TITLE
Movie images

### ISSUE THREAD

**Issue by arvazzz** [LordMike/TMDbLib#66]
Hello, i have been using your API for a while know and i can't solve 1 problem.
How can i get images from certain movie?
TMDbLib.Objects.Movies.Movie oMDetails = client.GetMovie(mID);
public System.Collections.Generic.List<TMDbLib.Objects.General.ImageData> ImagesPosters { get; set; }
magesPosters = oMDetails.Images.Posters;

I have tried ....General.Image data type and it still did not work. I am receiving this error: 
System.NullReferenceException: Object reference not set to an instance of an object.

Wonderful api but there is pretty much no documentation

**Comment by arvazzz** [comment]
Alright, i found a workaround by creating this
TMDbLib.Objects.General.ImagesWithId pim = client.GetMovieImages(id);
Thanks anyway by creating this great api

**Comment by LordMike** [comment]
I can concur on the documentation part. But iirc there should be an overload to GetMovie that allows you to specify extra types of data that you want.

It should get you the data you need.

-----Original Message-----

**Comment by arvazzz** [comment]
Another question, how do i use TMDbLib.Objects.General.Crew?

**Comment by arvazzz** [comment]
Could you give a short example how to get movie credits?

**Comment by LordMike** [comment]
There is an overload which accepts a `MovieMethods` enum which is also a `flag` type. So you can combine multiple requests in one. See below.

    client.GetMovie(movieId, MovieMethods.Images | MovieMethods.Credits)

This will fill out the respective fields which used to be `null`.

**Comment by joebob49** [comment]
Here's my snippet which does the job in VB.

Lookup/Update/Insert do as expected to two MYSQL database tables. One of the Actor details and the other to which connects actor(s) to movie(s). 

        '' CAST
        Dim MovieCast As TMDbLib.Objects.Movies.Credits = URLResponse.GetMovieCredits(Movie.Id)
        If Not IsNothing(MovieCast) Then
          For Each CastMemeber In MovieCast.Cast
            WriteConsolus("CastId: " & Convert.ToString(CastMemeber.CastId).PadLeft(10) & _
                vbTab & "ID: " & Convert.ToString(CastMemeber.Id).PadLeft(10) & _
                vbTab & "Actor: " & CastMemeber.Name.Trim(" ").PadRight(40) & _
                vbTab & "Character: " & CastMemeber.Character.Trim(" ").PadRight(30))

              Dim Actor_ID As Integer = ActorData.lookupActor(CastMemeber.Id)
              If Actor_ID > 0 Then '> 0 if found
                Actor_ID = ActorData.updateActor(Actor_ID, CastMemeber.Id, CastMemeber.Name, CastMemeber.ProfilePath)
              Else
                Actor_ID = ActorData.insertActor(CastMemeber.Id, CastMemeber.Name, CastMemeber.ProfilePath)
              End If

              ' UPDATE ACTOR IMAGE
              If Not IsNothing(CastMemeber.ProfilePath) Then
                picPoster.Image = GetWebImage(URLImageBase & CastMemeber.ProfilePath)
                picPoster.Refresh()
                Me.Refresh()
                UpdateActorImage(CastMemeber.Id) ' Image stored as a blob in actors table
              End If

              Dim MovieActor_ID = lookupMovieActor(Movie.Id, CastMemeber.Id)
              If MovieActor_ID > 0 Then '> 0 if found
                updateMovieActor(MovieActor_ID, Movie.Id, CastMemeber.Id, CastMemeber.Character, CastMemeber.CastId)
              Else
                insertMovieActor(Movie.Id, CastMemeber.Id, CastMemeber.Character, CastMemeber.CastId)
              End If
              Application.DoEvents()
          Next
         ' Displays info in listbox of movie's actors 
          Dim Actors As DataTable = lookupAllMovieActors(Movie.Id)
          ltbActors.DataSource = Actors
          ltbActors.DisplayMember = Actors.Columns("Fullname").ColumnName

URLresponse and URLImagebase are prebuilt as per TMDB api requirements.

**Comment by arvazzz** [comment]
Thanks, got credits/images/keyword/trailers working but now i can't figure out how to work with TMdbLib.Objects.Movie.Country

**Comment by LordMike** [comment]
I'm unsure about the question. The `Country` object is a single country, identified by its [`ISO 3166-1`](https://en.wikipedia.org/wiki/ISO_3166-1) code.. 

From the `Movie` object, it is found through a `Releases` collection.

**Comment by LordMike** [comment]
Closing this.
