### ISSUE TITLE
Overview in spanish language

### ISSUE THREAD

**Issue by javaman63** [LordMike/TMDbLib#67]
Hey this is a GREAT api lib!

How i can get an overview or any other data from the api in spanish language?

**Comment by LordMike** [comment]
Many of the methods allow you to specify languages. Is there a specific function you're in doubt about?
Also, do note that not all items at TMDb are available in Spanish.

**Comment by javaman63** [comment]
Hey mike! thanx for answer!
Yeah, that's my problem -> "do note that not all items at TMDb are available in Spanish.".

I've trying with the getmovie method with "spa" as a language and the overview property keep it coming null. 
So the problem is with the TMDB and not with your OUTSTANDING api lib!

**Comment by LordMike** [comment]
I'm unsure of the `spa` language. The Language codes are afaik. [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1), in which `Spain` is listed as `es`

**Comment by LordMike** [comment]
Closing this.
