### ISSUE TITLE
Error: People.person (birthday as year only)

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#68]
Lordmike;

I found a very early TMDB actor record (231) which only contained the year in the birthday field. People.person object throw a datetime error and nothing in the resulting object.  (I would have expected this to be a "date" type not a "datetime" type BTW).  I changed TMDB's record to the whole date YYYY-MM-DD resulting in proper response results. Any chance this object can be adjusted to allow just a year as well as a full date?

Regards; Joe

**Comment by joebob49** [comment]
Lordmike;

Found other culprits like the above at TMDB records 702, 766, 833. I will not edit these TMDB records for now so you can have the test hits. 

Joe

**Comment by Naliath** [comment]
Changing this would be possible but it would either leaving the field as a string or doing some custom deserialization for this. In my opinion the use case is so small that I think it's not worth the exception. In all honesty the API should be sending back the correct response format.

**Comment by LordMike** [comment]
I'll poke TMDb about this.

**Comment by Paszt** [comment]
There are currently about 2,194 people with either an incomplete birthday, day of death, or both. By incomplete I mean only the year.  And it's possible to add more dates with just the year.  The expected format is iso-8601 YYYY(-MM-DD), parenthesis around the month and day mean they are optional, of course.  
 
In my opinion, this is how the database should be designed.  With historical data, the exact date isn't always known and a database should be able to accept only the year. I wish the movie & TV release date were setup this way instead of having to input bogus information when the exact date isn't known (xxxx-01-01 or xxxx-12-31 for examples).

Here's a spreadsheet of the people with incomplete dates, last updates two days ago: https://docs.google.com/spreadsheets/d/1LGIlLxXEkb2g9zLVeESBFB41-UVZk_wAnod31QV1K5Q/edit?usp=sharing

**Comment by Naliath** [comment]
this is a bit of a pain. A .NET date has to have all criteria so this basicly means we can't parse it a such... It is an issue because you loose a part of date localization. ex here in Belgium and much of europe we write a date dd/mm/yyyy not mm/dd/yyyy. But as it stands the only easy way to fix this is to have the field as a string. Else we have to start with dual fields, a nullable date field and a year field as a string. Then we can have a helper field that does something like dateField.ToString() ?? yearString

**Comment by LordMike** [comment]
How about a string field and a DateTime conversion helper?
The helper could either be an extension method or a method directly on the class(es), which would then do hacks (such as setting month and day to 1 for dates with only years..).

**Comment by LordMike** [comment]
We could always go all-crazy and have a special TMDbDate object which can be either a year or a full date. We'd then overload comparisons so that it's easy to use when comparing with other DateTime objects.. 

When we only have the year, comparions would go like this (we assume that having only a year means the entire year is covered. Luckily, C# makes it easy to overload operators :).
new TMDbDate(1990) == new DateTime(1990, 7, 2)
new TMDbDate(1992) != new DateTime(1990, 7, 2)
new TMDbDate(1997) > new DateTime(1990, 7, 2)

**Comment by LordMike** [comment]
@Naliath, @joebob49, @Paszt .. please comment on the previous commit on the branch `issue-68` (f9d1a5e792ab9e66ccab119aaa8b3064100fe708). I've linked up `Person` to the new Date type. The tests ensure that comparisons work as expected (as I detailed in my previous comment).

**Comment by LordMike** [comment]
It could seem like the faulty dates for the `person` objects are being wiped. The code I made would therefore not apply to Person (at least for birth- and deathdates).

But it should be possible to use the concept elsewhere, where exact dates are not guaranteed.

**Comment by joebob49** [comment]
Just posted this at TMDB

Mike and Travis;

I setup two fields in my database, one for the movie_ year (integer) only in the movie record and the other for the release date (date) in the movie_releases record.Then I can search/etc. as needed. This seems to be a reasonable solution as I can validate on (integer) (range) or (date) as required. This would be consistent with "original language" and "spoken language" logic. To populate my movie_year field from TMDB I used year(release_date) if the latter validates as (date).
Ignore it!

A word of caution guys;

Having worked with VERY large Db's (up to 100 Million records) which where public input databases the best solution is NOT to input/store dates in the whole but as three separate fields; Year (validates as integer range 1800 to #### (where #### is typically year(now()), Month as integer range 1-12, Day as integer range (1-31). So the user is trapped into entering a validate year, or year and month, or year, month, day (Three inputs on form.) There will be no data loss in altering the table if done in three passes. Add the new fields, populate from the old field and then drop the old field, If Date of Birth and Date of Death are involved the former must be less than the latter. If the month or day are not used they default to NULL. If a developer wishes to rejoin into a date type they can where possible from the three fields only if all are valid.

BTW, the same is true for items like "Fullname". Names should be stored as Surname, Forename(s), and (Middle Names/Initials). If thought through this makes perfect sense.

Regards;
Joe

**Comment by Naliath** [comment]
@LordMike I'm not a big fan of a custom type in this situation but if it works, it works. I think it's key to just keep it simple for average users to consume the api.

@joebob49 While I get the argument of storing it a separate fields (mainframe style) it makes consumption of the api less user friendly. Then again the approach they took in making this a less than normal datatype. It's a date, but not all the time is not great either and the field per date type of solution would of been preferable if you are going to allow this type of input.

**Comment by joebob49** [comment]
Mike, Naliath. et al;

I looked at your new code. Sorry to say but this is not really "fixing" any of the date problems. The solution is really with TMDB using a more refined data structure. Naliath; An easy fix is really never the best solution as it will come back and bite your sooner or later. Nore is "less friendly". When there is a job to be done use the best solution not the cheapest/easiest. Please consider the value of TMDB to the end user. They are the consumers are they not? "It's a date" is not really true if there are latency records where the data is an integer or future input by the user can only be a year because that's all they have. Better a year than nothing here because as you know movie titles/ people's names are not unique so some kind of tie braker is required. So allow the input as such....

Joe

**Comment by Naliath** [comment]
@joebob49 I'm not talking about an easy fix as a long term solution (deserializing it as a string will make it work now with little to no effort of our part and get you the data). I'm talking about an easy interface for the user to consume. The way Mike is trying to fix it is actually the best .net way, it might not be complete yet but what he is trying to do is to mimic the 'complex' data structure exposed by TMDb, while still allowing for localization (date formatting) to work.

**Comment by LordMike** [comment]
Using .NET's DateTime is THE best way to handle dates. It makes the API easy to use, everywhere, as dates are understood and well-used. When exposing something that doesn't fit in the DateTime class, we have to do something to make it work. I think my approach of making something that mimics DateTime, but isn't, is the best compromise to keeping it usable.

There are a number of places in TMDb where dates are used. It seems that Travis is ok with wiping the Person dates that are incomplete - which is a really good solution long term (as we fall back to a stricter type). My code is therefore made obsolete in this matter.

Other dates though, might still be only years, in which my code still applies. We just need to evaluate for each case if we need to present it as DateTime (strict format with full dates) or as a TMDbDate (not so strict format).

**Comment by joebob49** [comment]
Naliath;

Ok that I can live with providing a real solution is forthcoming from TMDB. TMDB and it's users are the source of the data and until the problem(s) are resolved there there will be no real solution. Mike, Please impress upon Travis NOT to destroy any data. put it to the side but do preserve it. I'm sorry to be bit old school and a profectionist but "I is what I is". 

Joe

**Comment by LordMike** [comment]
@joebob49 put your 2-cents into the discussion at https://www.themoviedb.org/talk/556a091992514173f5001af6 so that I'm not the only one in there chatting :P

**Comment by agoretsky** [comment]
@LordMike, how about temporary ignore error of this particular field to provide object with all another fields instead of exception?
Like this:

        public class Test
        {
            [JsonProperty("date")]
            public DateTime? MyDate { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }
        }

        public static void Main(string[] args)
        {
            var str = "{\"date\":1954, \"name\":\"test\"}";

            var settings = new JsonSerializerSettings
            {
                Error = (serializer, errorEventArgs) =>
                {
                    if (errorEventArgs.ErrorContext.Path == "date")
                    {
                        errorEventArgs.ErrorContext.Handled = true;
                    }
                }
            };

            var result = JsonConvert.DeserializeObject<Test>(str, settings);
        }

**Comment by LordMike** [comment]
@agoretsky check out [0.9.1.3-alpha](https://www.nuget.org/packages/TMDbLib/0.9.1.3-alpha).

**Comment by agoretsky** [comment]
@LordMike, thank you!
