### ISSUE TITLE
TmDbLib complains that v104.4.0.0 of RestSharp is not installed

### ISSUE THREAD

**Issue by BO45** [LordMike/TMDbLib#69]
This is with version 0.8.1-alpha and latest stable.

**Comment by LordMike** [comment]
How does one fix this (and other version-related things)?

**Comment by Naliath** [comment]
<dependency id="RestSharp" version="104.4.0.0" />

would fix this, you can also define min versions, allow minor version changes, etc.. 
https://docs.nuget.org/create/versioning

**Comment by LordMike** [comment]
@Naliath that's in the Nuget package, right?

**Comment by Naliath** [comment]
in the nuspec file yea

**Comment by LordMike** [comment]
It's weird. But I've published `0.8.2-alpha` to Nuget.

**Comment by Naliath** [comment]
this should make it so that any restsharp version from that version on is supported by us

**Comment by LordMike** [comment]
The point is that it was already listed as dependency, just without any version... but let's see how this fares.
