### ISSUE TITLE
MovieMethods.Casts does not exist?

### ISSUE THREAD

**Issue by joelp53** [LordMike/TMDbLib#70]
Trying out your API, so far I am very impressed. 
Looking through everything you have avilable, I notice you are missing Casts. 
Not sure if a big or if I am doing something wrong. 

I have all relevent libaries loaded and I am currently using the stable version.
Installed it via NuGet as you sugest.

**Comment by Naliath** [comment]
That's quite possible, it might have been added 'recently'. You  do have the credits specifier that might get you what you need. We do have a few outstanding methods around people that have not been implemented.

**Comment by LordMike** [comment]
Wrote to TMDb here: https://www.themoviedb.org/talk/5569d327c3a368774e0019fc

Did some investigating, and it seems to be identical with Credits. Will wait on reply and branch of my "fix" ... :).

**Comment by LordMike** [comment]
@joelp53 TMDb have discontinued usage of the `casts` method. So it will not be implemented.
Use `credits` instead.
