### ISSUE TITLE
.GetMovieReleases(Movie.Id) missing "primary" 

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#71]
Lordmike;

Thanks for the speedy updates to missing movie items and post to nuget. Works just fine thx!

Found a missing item in getmoviereleases method. Nothing for boolean "Primary". This is the 'first release country' record flag. 

Pls do have a look see.

Thx Joe

**Comment by Naliath** [comment]
https://github.com/LordMike/TMDbLib/commit/5f14cc7d895060f7e5d3388aad7e34ee03522cff
