### ISSUE TITLE
DefaultLanguage does not work in GetTrailers(tmdbID) and GetCollection(tmdbID)

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#74]
HI

i always create a new API object in this way:
_TMDBApi = New TMDbLib.Client.TMDbClient(Settings.ApiKey)
_TMDBApi.GetConfig()
_TMDBApi.DefaultLanguage = Settings.PrefLanguage

It works with:
_TMDBApi.GetMovie(tmdbID)
_TMDBApi.GetCollection(tmdbID, _MySettings.PrefLanguage)
_TMDBApi.GetMovie(tmdbID, TMDbLib.Objects.Movies.MovieMethods.Trailers).Trailers

But it does not work (always english results):
_TMDBApi.GetCollection(tmdbID)
_TMDBApi.GetTrailers(tmdbID)

Is this intended or a bug?

**Comment by Naliath** [comment]
Bug: quick look into the overloads leads me to this => return GetCollection(collectionId, null, extraMethods);

**Comment by Naliath** [comment]
see fix https://github.com/LordMike/TMDbLib/commit/5f14cc7d895060f7e5d3388aad7e34ee03522cff
Couldn't find the GetTrailers thing you speak off, just submit a pull request for it if you locate it

**Comment by DanCooper** [comment]
Thank you for fixing.

it's the "public Trailers GetMovieTrailers(int movieId)" thing.

**Comment by Naliath** [comment]
That impacts all other sub methods as well. I think we can just assume that if it's null we need to set the default language and if that is not set it will just be ignored. Won't do that fix from my browser, need to be able to run the tests. I'll get to it when I get home later today.

**Comment by LordMike** [comment]
I see. So in theory, we should always set DefaultLanguage at the lowest levels, if the provided language is `null`? 

One such place: https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/Client/TMDbClientMovies.cs#L111

**Comment by DanCooper** [comment]
I would say YES.

**Comment by Naliath** [comment]
This should fix it: https://github.com/LordMike/TMDbLib/commit/255b7847b8d1408cdcac1d56e2e51e5217b0f269

**Comment by LordMike** [comment]
Was just working on that, spotted some issues in the tests though so went out to fix that.. Will check up on your changes @Naliath.

**Comment by LordMike** [comment]
Seems good :+1:
