### ISSUE TITLE
GetMovie Null..why?

### ISSUE THREAD

**Issue by javaman63** [LordMike/TMDbLib#76]
Hi Mike! For some movies, the method GetMovie return a object with null propertys
![captura de pantalla 2015-05-30 12 41 31](https://cloud.githubusercontent.com/assets/8239681/7898027/8dc4f8f8-06c9-11e5-865d-008fa83e7019.png)
Can you tell me why or help me?

Thanx!

**Comment by LordMike** [comment]
Hi,

The GetMovie method is very generic and will suit a lot of situations. You already add the Images method, but you can add many more. You could f.ex. do:

`Movie movie = client.GetMovie(movieId, MovieMethods.Images | MovieMethods.Credits);`

Regards,
Mike.

**Comment by javaman63** [comment]
Yes! but for some movies...return nothing, but when you search in the webpage, the movie is there with images, cast, credits, etc..thats my question...

Ex:
for IMDBID: "tt1823672"..returns everything OK
     IMDBID: "tt304141"..returns null

why?

**Comment by LordMike** [comment]
Perhaps the data isn't there. IMDb id's don't always work as expected.

See the links below:
https://www.themoviedb.org/search?query=tt1823672
https://www.themoviedb.org/search?query=tt304141

**Comment by javaman63** [comment]
AHH ok!!! Perfect! Thank's for helping me!

Close this if you want!
