### ISSUE TITLE
Missing: /person/{id}/external_ids 

### ISSUE THREAD

**Issue by DanCooper** [LordMike/TMDbLib#77]
Hi
Thank you for the latest updates!

Found another thing that looks like it missing in TMDBLib.
Please add it if you have time.

http://docs.themoviedb.apiary.io/reference/people/personidexternalids

**Comment by LordMike** [comment]
This is underway. I just looked at the person methods yesterday, and I definitely did some work on external ids.

Check out the pull request related to it, to confirm.

Mike.

-----Original Message-----

**Comment by DanCooper** [comment]
Great, thank you so much.
I don't know, but is there a way to get TVShow informations with Credits including ExternalIDs instead of GetExternalIDs for each Credit (i hope you understand what i mean)?

I use

GetTvShow(ID, TMDbLib.Objects.TvShows.TvShowMethods.ContentRatings Or TMDbLib.Objects.TvShows.TvShowMethods.Credits Or TMDbLib.Objects.TvShows.TvShowMethods.ExternalIds)

to get all informations that i need in one API call. But it's also possible to get the Credits-ExternalIDs in the same API call?

**Comment by LordMike** [comment]
It seems that you already OR the methods together, meaning you should be getting it all in one go. Are you certain its not there?

In many cases, its helpful to have Fiddler or another proxy running in the background, to help decipher what's going on.

That being said. I can't remember if there were any bugs in the external id implementation for person.

-----Original Message-----

**Comment by DanCooper** [comment]
My code works, "OR" is the right way to get this three "extraMethods".
I have to test your new commits and try it again.

**Comment by LordMike** [comment]
I just checked up on it. 
The External ID's are not available in the current `master`, but it has been implemented in my re-vamp of the library. It will come in as soon as the merge request #123 is accepted.

The underlying issue, which I'll close this and refer to, is #104. 

Reference, test from #123:
https://github.com/LordMike/TMDbLib/blob/issue-104/TMDbLibTests/ClientPersonTests.cs#L171
