### ISSUE TITLE
Primary Release [Boolean]?

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#78]
Hi Mike;

Did I miss something in Movie.Releases or is the Primary Release flag [boolean] not in the Movies.releases collection? I see it in the apiary doc. 

Regards;
Joe

**Comment by LordMike** [comment]
You're talking about the `primary_release_year` fields and filters?

**Comment by LordMike** [comment]
Ah I see now.

**Comment by LordMike** [comment]
Are you certain?
The `Country` object has a `Primary` boolean attached, which should be populated. 

@joebob49 please comment on this.

**Comment by joebob49** [comment]
I'll have a closer look and see just where the "Primary" flag should appear. My understanding from a TMDB moderator is that the "Primary" release is/can be used to determine just what applies as "Original Language" criteria. The "Primary" release country (language) being one of the factors of the discussion.  

"So if yours is the criteria upon which original language is decided then please explain why anyone could/would set and lock this field as English in "Fist full of Dollars" when the movie was Produced it Italy, First (Primary} release was 12 September 1964 in Italy and was NOT released in any English speaking country until Canada on 22 December 1966. It was NOT released in the USA until 18 January 1967. That's 2-3 years after it's release in Italy (An Italian speaking country if I'm not mistaken). Then released in: blah, blah, blah"

I'll look at the country object but when scraping releases would it not require and pass to examine countries? Can of redundant when the flag is returned as part of the releases object?

Standby while I have a closer look see! 

Joe

**Comment by joebob49** [comment]
Mike;

It is in the /movie/releases json. Example:
{
  "id": 550,
  "countries": [
    {
      "certification": "R",
      "iso_3166_1": "US",
      "primary": true,
      "release_date": "1999-10-14"
    },
    {
      "certification": "18",
      "iso_3166_1": "DE",
      "primary": false,
      "release_date": "1999-11-10"
    },

I see what you are looking at in "Discover". Here it is a filter item and does not provide the actual flag in the json. No help when scraping movies/releaes by TMDB id and wishing to record the flag status locally.

If other data settings (i.e. Original Language) is/are to be premised on this flag the it certainly is required or validation, if nothing else.

FYI: I am getting the impression that you think my application is a real-time lookup front end to TMDB. Not so. I have a SQL database backend running which augments their data with my own. I also am starting to check data for: stats, error & omissions, exceptions, etc.

Joe

**Comment by joebob49** [comment]
Sorry seem to have mixed up my "Issues" Last version I have is 8.1 alpha and 8.2 isn't showing on Nuget. Any suggestions?

BTW can we/I get on a mailing list somewhere to be notified when updates occur?

Joe

**Comment by LordMike** [comment]
There is no mailing list :P
But I can see that Naliath added the field 16 days ago here ffc2eacec2b2bea397c0f723ddc72e5910114995, so it should have made it into the 0.8.2-alpha.

You can get the 0.8.2-alpha by visiting here: https://www.nuget.org/packages/TMDbLib/0.8.2-alpha, or by running this command in the Package Console: 

Install-Package TMDbLib -Pre

**Comment by joebob49** [comment]
Thanks!

Have it through the nuget console!

Don't understand why it was not in the NUGET updates (VS13 btw) . Because it's a pre-release?

Joe

**Comment by LordMike** [comment]
Pre-release. Yes.

**Comment by Naliath** [comment]
yea you have to either use the console or the dropdown in the packagemanager to allow prereleases

**Comment by LordMike** [comment]
I take it this issue has been handled @joebob49 ?

At least it revealed some missing code elsewhere :)

Also, I don't have a timeline for an official release yet. I suppose the next official release will include the async changes we've been looking at lately, and therefore it will take some time and be breaking.

**Comment by joebob49** [comment]
Yup!
Have the update and am adjusting my code now. Thanks Much!

Joe
