### ISSUE TITLE
Trailers Problem

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#79]
Mike;

Did I miss something because I'm not getting all the info through the wrapper?

Raw:
https://api.themoviedb.org/3/movie/78/videos?api_key=MYKEY

{
  "id": 78,
  "results": [
    {
      "id": "533ec651c3a3685448000089",
      "iso_639_1": "en",
      "key": "xP4WvJaMfj8",
      "name": "Trailer 1",
      "site": "YouTube",
      "size": 480,
      "type": "Trailer"
    },
    {
      "id": "533ec651c3a368544800008a",
      "iso_639_1": "en",
      "key": "PSIiGE105iA",
      "name": "Harrison Ford On Blade Runner",
      "site": "YouTube",
      "size": 480,
      "type": "Featurette"
    },
    {
      "id": "533ec651c3a368544800008b",
      "iso_639_1": "en",
      "key": "IbhFZihpGfY",
      "name": "Rutger Hauer Blade Runner",
      "site": "YouTube",
      "size": 360,
      "type": "Featurette"
    },

I am assuming that "id" is the unique index field for each item which you appear to be missing in the method, that "key" here = "source" in the wrapper I assume, "type" looks new. Please see the Apiary.

Joe

**Comment by LordMike** [comment]
I'm recalling not being able to test trailers fully because it wasn't so popular or filled out back then.

**Comment by joebob49** [comment]
I've been scraping and checking this data coming through the wrapper (is it is since last release) and be aware that Travis was (and may not yet) be sanitizing the "key" field for code injections. I've notified him of the problem and it is now on a ticket. 

I don't see any unique key in his trailers per movie json (above) unless he is using  the "ID" entry (i.e. "id": "533ec651c3a3685448000089",) as his unique key. Don't yet know why it's not an integer. 

Anyhow, please advise me if/when wrapper changes may be forthcoming on this and my prior issue post related the "Primary Release" flag in Movie.Releases.

Joe

**Comment by LordMike** [comment]
@joebob49 check out my branch, issue-79.

https://github.com/LordMike/TMDbLib/commits/issue-79

**Comment by joebob49** [comment]
Oops, Am I a wrapper release behind? I'll check my version!

Ouch! I am one behind. (8.1 Alpha). I'll Update! Nope. Last on Nuget is this one. Cannot seem to get 8.2 Alpha there.  Help?

Joe

**Comment by LordMike** [comment]
@joebob49 no - I meant look at my code, see if that would work for you. I found we missed a set of properties on the Video and Trailer objects. So it's been remedied.

**Comment by Naliath** [comment]
Yea stuff get's added all the time. I'm quite sure not all those props were available when we implemented the feature

**Comment by LordMike** [comment]
With #82 merged in. I'm closing this. 

Thanks for reporting :)
