### ISSUE TITLE
The 8.2 alpha version and Trailers?

### ISSUE THREAD

**Issue by joebob49** [LordMike/TMDbLib#84]
Mike;

I cannot see the issue post I made on Trailers. I don't see a data match with json in your trailers object in the 8.2 alpha. .

Was this the additional "coding" you referred to earlier today?

Joe

**Comment by LordMike** [comment]
Yes. I can make an 8.2.1-alpha if you'd like?

For reference: #79

**Comment by joebob49** [comment]
Never mind. I see you closed it!

Joe

**Comment by joebob49** [comment]
Ok 
Please do and i'll test it! Will let you know the results

joe.

**Comment by LordMike** [comment]
@joebob49 it is now here https://www.nuget.org/packages/TMDbLib/0.8.2.1-alpha

Sorry about the delay. An emergency came up at work.

**Comment by joebob49** [comment]
Thanks Mike;

Must be Monday there. We're still on Sunday here on the sunny west Coast of Canada.

Anyway I'll update and get back to you when I've tested....

Joe

**Comment by joebob49** [comment]
Humm..

Not seeing any changes. Checked version and its 8.2.1
Using:
      Dim Movie_Trailers As TMDbLib.Objects.Movies.Trailers = URLResponse.GetMovieTrailers(Movie_id)

I was expecting something to containing this:
{
"id": 78,
"results": [
{
"id": "533ec651c3a3685448000089",
"iso_639_1": "en",
"key": "xP4WvJaMfj8",
"name": "Trailer 1",
"site": "YouTube",
"size": 480,
"type": "Trailer"
},
{
"id": "533ec651c3a368544800008a",
"iso_639_1": "en",
"key": "PSIiGE105iA",
"name": "Harrison Ford On Blade Runner",
"site": "YouTube",
"size": 480,
"type": "Featurette"
},

Not having the "id" is causing me a uniqueness problem in my DB table. All I see in the wrapper is; Name, Size, Key per trailer.

Pls advise...
Joe

**Comment by joebob49** [comment]
Found your code:

namespace TMDbLib.Objects.Movies
{
    public class Youtube
    {
        public string Name { get; set; }
        public string Size { get; set; }
        public string Source { get; set; }
    }
}

To:
        public string Id { get; set; }
        public string ISO-639-1  { get; set; }
        public string Site { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public string Source { get; set; }
        public string Type  { get; set; }

Though "type" as a var name I never liked! Too generic for starters. I rather prefer your "source" to Travis's "key". Your "Standard" or "HD" seems enough and more understandable that numeric sizes.

Joe

**Comment by LordMike** [comment]
It didn't change?
Must've messed up. :-o

I'll take a look at it when I get back home this evening.

**Comment by LordMike** [comment]
Ah. I see now. I completely messed up when I did the two pull requests last night.

**Comment by LordMike** [comment]
I can also see now that the `/trailers` has been deprecated in favor of `/videos`.

**Comment by LordMike** [comment]
Arh screw it. We haven't made a full release since `0.7.7`, so we can break stuff.

**Comment by LordMike** [comment]
@joebob49 I'll try to make an 0.8.2.2-alpha.

**Comment by LordMike** [comment]
@joebob49 an 0.8.2.2-alpha should be out.
https://www.nuget.org/packages/TMDbLib/0.8.2.2-alpha

**Comment by joebob49** [comment]
Mike;

Something isn't right! I expected:

      Dim Movie_Trailers As TMDbLib.Objects.General.Video = URLResponse.GetMovieVideos(Movie_id)

But the method and the container are not agreeing. I looked at your code and see:

namespace TMDbLib.Objects.General
{
    public class Video
    {
        public string Id { get; set; }
        public string Iso_639_1 { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Site { get; set; }
        public int Size { get; set; }
        public string Type { get; set; }
    }
}
Which looks good btw.

Hah! Got it....

      public ResultContainer<Video> Videos { get; set; }

Right? So:
      Dim Movie_Trailers As TMDbLib.Objects.General.ResultContainer(Of TMDbLib.Objects.General.Video) = URLResponse.GetMovieVideos(Movie_id)

Joe

**Comment by LordMike** [comment]
Wow, VB looks verbose :P
Did it work out for you?

**Comment by joebob49** [comment]
I'll be testing in a bit. have to alter my table to match new model. May take a bit as it will take three passes at least if I am to retain any fragment of my current data. ~250,000 records.

I'll let you know the results.

Joe

**Comment by joebob49** [comment]
Mike;

Looks just fine thanks!

Joe

**Comment by LordMike** [comment]
Cool. Remember, quite a few methods will shift places and change names over the next days and weeks, until we can get 0.8.3 out. I'll continue making 0.8.2.x builds until then.

**Comment by joebob49** [comment]
Thanks I'll check daily...

Joe
