### ISSUE TITLE
Configuration - Verify that all methods are implemented

### ISSUE THREAD

**Issue by LordMike** [LordMike/TMDbLib#87]
Verify that all methods below have been implemented.

Configuration
- [x] /configuration

**Comment by scavarda** [comment]
I can't find any client method for "http://api.themoviedb.org/3/configuration/jobs"
Where is it?
tnx

**Comment by LordMike** [comment]
It's entirely possible that method is completely new. In #200, we asked TMDb, and the just recently replied back that they now have methods for languages etc. They lie in the same namespace as Jobs.
